using System.Globalization;
using Pikslovo.Core;

namespace Pikslovo;

public static class AppStrings
{
    private static AppLanguageMode _languageMode = AppLanguageMode.System;

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Tłumacz"] = "Translator",
        ["Wróć do ustawień"] = "Back to settings",
        ["Ustawienia"] = "Settings",
        ["Uprawnienia"] = "Permissions",
        ["Nakładka nad grą i powiadomienia"] = "In-game overlay and notifications",
        ["Klucz do rozpoznawania i tłumaczenia tekstu"] = "Key for text recognition and translation",
        ["Tłumaczenie"] = "Translation",
        ["Języki źródłowy i docelowy"] = "Source and target languages",
        ["Globalny hotkey"] = "Global hotkey",
        ["Skrót do pokazywania tłumaczenia"] = "Shortcut to show the translation",
        ["Przycisk pływający"] = "Floating button",
        ["Widoczność, rozmiar i pozycja na ekranie"] = "Visibility, size and position on screen",
        ["Przetwarzanie tekstu"] = "Text processing",
        ["Pewność OCR, skala obrazu, łączenie dialogów i nakładka"] = "OCR confidence, image scale, dialog grouping and overlay",
        ["Wygląd aplikacji"] = "App appearance",
        ["Konfiguracje"] = "Configurations",
        ["Eksportuj ustawienia"] = "Export settings",
        ["Zapisz OCR, kompresję JPEG, obszar i przycisk do pliku JSON."] = "Save OCR, JPEG compression, region and button settings to a JSON file.",
        ["Importuj ustawienia"] = "Import settings",
        ["Wczytaj OCR, kompresję JPEG i pozostałą konfigurację z pliku JSON."] = "Load OCR, JPEG compression and the remaining configuration from a JSON file.",
        ["Przywróć domyślne"] = "Restore defaults",
        ["Wyczyść OCR wraz z kompresją JPEG, obszarem i przyciskiem."] = "Clear OCR, JPEG compression, region and button settings.",
        ["Wsparcie"] = "Support",
        ["Diagnostyka"] = "Diagnostics",
        ["Ostatnie czasy tłumaczenia i sprawdzenia klucza API"] = "Latest translation and API key validation timings",
        ["Eksportuj dziennik diagnostyczny"] = "Export diagnostics log",
        ["Zapisz bezpieczny raport z pomiarami, bez klucza API i treści ekranu."] = "Save a safe report with measurements, without the API key or screen content.",
        ["Język źródłowy"] = "Source language",
        ["Język docelowy"] = "Target language",
        ["Klucz jest szyfrowany lokalnie w Android Keystore."] = "The key is encrypted locally in Android Keystore.",
        ["Pokaż lub ukryj klucz API"] = "Show or hide API key",
        ["Uzyskaj klucz Google Cloud API"] = "Get a Google Cloud API key",
        ["Pewność rozpoznawania"] = "Recognition confidence",
        ["Skala obrazu OCR"] = "OCR image scale",
        ["Kompresuj obraz OCR do JPEG"] = "Compress OCR image to JPEG",
        ["Zmniejsza dane wysyłane do Google Cloud."] = "Reduces data sent to Google Cloud.",
        ["Jakość JPEG"] = "JPEG quality",
        ["Siła łączenia tekstu"] = "Text grouping strength",
        ["Skalowanie czcionki"] = "Font scale",
        ["Ukrywaj identyczne tłumaczenia"] = "Hide identical translations",
        ["Nie pokazuj tekstu, gdy tłumaczenie jest takie samo."] = "Do not show text when the translation is identical.",
        ["Ustawienia dostępności"] = "Accessibility settings",
        ["Włącz usługę systemową dla globalnego hotkeya."] = "Enable the system service for the global hotkey.",
        ["Włącz globalny hotkey"] = "Enable global hotkey",
        ["Pozwala wywołać tłumaczenie poza aplikacją."] = "Lets you trigger translation outside the app.",
        ["Klawisz skrótu"] = "Shortcut key",
        ["Zawsze pokazuj przycisk"] = "Always show button",
        ["Rozmiar przycisku"] = "Button size",
        ["Pozycja pozioma"] = "Horizontal position",
        ["Pozycja pionowa"] = "Vertical position",
        ["Nakładka nad grą"] = "In-game overlay",
        ["Zezwól aplikacji wyświetlać tłumaczenie nad innymi aplikacjami."] = "Allow the app to display translations over other apps.",
        ["Powiadomienia"] = "Notifications",
        ["Zezwól na powiadomienie o aktywnej sesji tłumacza."] = "Allow notifications about the active translator session.",
        ["Ostatnie tłumaczenie"] = "Latest translation",
        ["Pomiar jest aktualizowany po zakończeniu tłumaczenia."] = "Measurements are updated when translation completes.",
        ["Przechwycenie + kodowanie"] = "Capture + encoding",
        ["Kodowanie obrazu OCR"] = "OCR image encoding",
        ["Całość"] = "Total",
        ["Ostatnie sprawdzenie klucza API"] = "Latest API key validation",
        ["Motyw"] = "Theme",
        ["System"] = "System",
        ["Ciemny"] = "Dark",
        ["Jasny"] = "Light",
        ["Akcent"] = "Accent",
        ["Język aplikacji"] = "App language",
        ["English"] = "English",
        ["Polski"] = "Polish",
        ["Systemowy"] = "System default",
        ["Koralowy"] = "Coral",
        ["Bursztynowy"] = "Amber",
        ["Limonkowy"] = "Lime",
        ["Miętowy"] = "Mint",
        ["Morski"] = "Teal",
        ["Błękitny"] = "Sky blue",
        ["Stalowy"] = "Steel",
        ["Orchidea"] = "Orchid",
        ["Różowy"] = "Rose",
        ["Lawendowy"] = "Lavender",
        ["Brak pomiaru"] = "No measurement",
        ["Witaj w Pikslovo"] = "Welcome to Pikslovo",
        ["Pikslovo rozpoznaje tekst na ekranie gry i tłumaczy go przez Google Cloud. Zrzut ekranu oraz rozpoznany tekst są wysyłane do usług Google tylko podczas tłumaczenia."] = "Pikslovo recognizes text on your game screen and translates it with Google Cloud. The screenshot and recognized text are sent to Google services only while translating.",
        ["Języki"] = "Languages",
        ["Podczas aktywnej sesji Android wyświetla stałe powiadomienie. Informuje ono, że Pikslovo może przechwytywać ekran na potrzeby tłumaczenia."] = "During an active session, Android displays a persistent notification. It indicates that Pikslovo can capture the screen for translation.",
        ["Widoczna aktywna sesja"] = "Visible active session",
        ["Powiadomienie pozostaje widoczne, gdy tłumacz działa w tle."] = "The notification remains visible while the translator runs in the background.",
        ["Kontrola sesji"] = "Session control",
        ["Z poziomu powiadomienia można zatrzymać aktywną sesję tłumacza."] = "You can stop the active translator session from the notification.",
        ["Pikslovo potrzebuje zgody na wyświetlanie nad innymi aplikacjami, aby pokazać przetłumaczony obraz bez wychodzenia z gry."] = "Pikslovo needs permission to display over other apps so it can show the translated image without leaving the game.",
        ["Tłumaczenie nad grą"] = "Translation over the game",
        ["Wynik pojawi się jako tymczasowa nakładka nad aktualnym ekranem."] = "The result will appear as a temporary overlay over the current screen.",
        ["Tylko na żądanie"] = "Only on demand",
        ["Nakładka jest pokazywana wyłącznie po wywołaniu tłumaczenia."] = "The overlay is shown only after translation is triggered.",
        ["Pikslovo wymaga własnego klucza Google Cloud API do rozpoznawania i tłumaczenia tekstu. Możesz skonfigurować go teraz albo później w ustawieniach. Bez klucza tłumaczenie nie będzie działać."] = "Pikslovo requires your own Google Cloud API key for text recognition and translation. You can configure it now or later in Settings. Translation will not work without it.",
        ["Kontynuuj"] = "Continue",
        ["Przyznaj uprawnienie"] = "Grant permission",
        ["Sprawdź klucz"] = "Check key",
        ["Sprawdzanie..."] = "Checking...",
        ["Nie można jeszcze odczytać ustawień: {0}"] = "Settings cannot be read yet: {0}",
        ["Nie wybrano"] = "Not selected",
        ["Japoński"] = "Japanese",
        ["Angielski"] = "English",
        ["Koreański"] = "Korean",
        ["Chiński (uproszczony)"] = "Chinese (Simplified)",
        ["Niemiecki"] = "German",
        ["Hiszpański"] = "Spanish",
        ["Brak klucza API"] = "Missing API key",
        ["Wpisz klucz Google Cloud API, aby go sprawdzić."] = "Enter a Google Cloud API key to check it.",
        ["Klucz nie działa"] = "Key does not work",
        ["Klucz nie ma dostępu do {0}. Sprawdź poprawność klucza oraz czy to API jest włączone w projekcie Google Cloud."] = "The key cannot access {0}. Check that the key is valid and that this API is enabled in the Google Cloud project.",
        ["Nie udało się sprawdzić dostępu do {0}. Usługa Google zwróciła błąd {1}."] = "Could not check access to {0}. Google returned error {1}.",
        ["Brak połączenia"] = "No connection",
        ["Nie udało się połączyć z Google Cloud. Sprawdź połączenie z Internetem i spróbuj ponownie."] = "Could not connect to Google Cloud. Check your internet connection and try again.",
        ["Limit czasu"] = "Timed out",
        ["Sprawdzenie klucza trwało zbyt długo. Spróbuj ponownie przy stabilnym połączeniu."] = "Key validation took too long. Try again with a stable connection.",
        ["Klucz działa"] = "Key works",
        ["Klucz ma dostęp do Cloud Translation API i Cloud Vision API."] = "The key can access Cloud Translation API and Cloud Vision API.",
        ["Zapisz"] = "Save",
        ["Anuluj"] = "Cancel",
        ["Zamknij"] = "Close",
        ["Przywróć"] = "Restore",
        ["Przywrócić ustawienia domyślne?"] = "Restore default settings?",
        ["Ta operacja wyczyści ustawienia OCR, JPEG, obszaru przechwytywania i przycisku pływającego. Klucz API, języki, hotkey i wygląd aplikacji pozostaną bez zmian."] = "This will clear OCR, JPEG, capture region and floating button settings. The API key, languages, hotkey and app appearance will remain unchanged.",
        ["Zostaną zresetowane ustawienia OCR, w tym kompresja JPEG i jakość obrazu, nakładka, obszar przechwytywania oraz przycisk pływający. Klucz API, języki, hotkey i wygląd aplikacji pozostaną bez zmian."] = "OCR settings, including JPEG compression and image quality, overlay, capture region and floating button will be reset. The API key, languages, hotkey and app appearance will remain unchanged.",
        ["Ustaw skrót"] = "Set shortcut",
        ["Przytrzymaj klawisz(e) przez 2 sekundy"] = "Hold key(s) for 2 seconds",
        ["Nie ustawiono"] = "Not set",
        ["Edytuj obszar przechwytywania"] = "Edit capture region",
        ["Zatrzymaj tłumacza"] = "Stop translator",
        ["Tłumaczenie w toku"] = "Translation in progress",
        ["Wróć do gry"] = "Return to game",
        ["Tłumacz ekran"] = "Translate screen",
        ["Przeciągnij narożniki obszaru dialogu"] = "Drag the dialog region corners",
        ["Zapisz obszar"] = "Save region",
        ["Anuluj wybór obszaru"] = "Cancel region selection",
        ["Udostępnij dziennik diagnostyczny"] = "Share diagnostics log",
        ["Nie można otworzyć panelu udostępniania."] = "Cannot open the share panel.",
        ["Aktywność Androida nie jest gotowa. Zamknij i otwórz aplikację ponownie."] = "Android activity is not ready. Close and reopen the app.",
        ["Aktywność Androida nie jest jeszcze gotowa."] = "Android activity is not ready yet.",
        ["Nie można otworzyć strony Google Cloud: {0}"] = "Cannot open the Google Cloud page: {0}",
        ["Nie można otworzyć wyboru pliku: {0}"] = "Cannot open the file picker: {0}",
        ["Nie można wyeksportować dziennika diagnostycznego: {0}"] = "Cannot export diagnostics log: {0}",
        ["Przywrócono domyślne ustawienia konfiguracji."] = "Default configuration settings restored.",
        ["Nie można przywrócić ustawień: {0}"] = "Cannot restore settings: {0}",
        ["Uprawnienie nakładki jest już przyznane."] = "Overlay permission is already granted.",
        ["Otwieram ustawienia nakładki Androida."] = "Opening Android overlay settings.",
        ["Nie można otworzyć ustawień nakładki: {0}"] = "Cannot open overlay settings: {0}",
        ["Uprawnienie powiadomień jest już przyznane."] = "Notification permission is already granted.",
        ["Wyświetlam prośbę Androida o zgodę na powiadomienia."] = "Showing Android's notification permission request.",
        ["Nie można poprosić o uprawnienie powiadomień: {0}"] = "Cannot request notification permission: {0}",
        ["Otwieram ustawienia dostępności Androida."] = "Opening Android accessibility settings.",
        ["Nie można otworzyć ustawień dostępności: {0}"] = "Cannot open accessibility settings: {0}",
        ["Zatrzymano sesję tłumacza."] = "Translator session stopped.",
        ["Otwieram dialog udostępniania ekranu Androida."] = "Opening Android's screen sharing dialog.",
        ["Nie można uruchomić przechwytywania ekranu: {0}"] = "Cannot start screen capture: {0}",
        ["Uprawnienie nie zostało przyznane. Możesz spróbować ponownie."] = "Permission was not granted. You can try again.",
        ["Nie można zapisać wybranego pliku."] = "Cannot save the selected file.",
        ["Nie można wyeksportować ustawień: {0}"] = "Cannot export settings: {0}",
        ["Nie można odczytać wybranego pliku."] = "Cannot read the selected file.",
        ["Nie można zaimportować ustawień: {0}"] = "Cannot import settings: {0}",
        ["Ustawienia wyeksportowano do pliku JSON."] = "Settings exported to a JSON file.",
        ["Ustawienia zaimportowano z pliku JSON."] = "Settings imported from a JSON file.",
        ["Ustaw skrót albo wyłącz globalny hotkey."] = "Set a shortcut or disable the global hotkey.",
        ["Wpisz klucz API i wybierz oba języki."] = "Enter an API key and select both languages.",
        ["W aktywnej sesji jest widoczny niezależnie od globalnego hotkeya."] = "It is visible during an active session regardless of the global hotkey.",
        ["W aktywnej sesji jest ukryty, gdy globalny hotkey jest włączony."] = "It is hidden during an active session when the global hotkey is enabled.",
        ["W aktywnej sesji jest widoczny, ponieważ globalny hotkey jest wyłączony."] = "It is visible during an active session because the global hotkey is disabled.",
        ["nieznana"] = "unknown",
        ["Pikslovo - raport diagnostyczny"] = "Pikslovo - diagnostics report",
        ["Wygenerowano (UTC): {0}"] = "Generated (UTC): {0}",
        ["Aplikacja: {0}"] = "Application: {0}",
        ["Urządzenie: {0}"] = "Device: {0}",
        ["Aktywna sesja tłumacza: {0}"] = "Active translator session: {0}",
        ["Uprawnienie nakładki: {0}"] = "Overlay permission: {0}",
        ["Uprawnienie powiadomień: {0}"] = "Notification permission: {0}",
        ["Ostatnie pomiary:"] = "Latest measurements:",
        ["Całość tłumaczenia"] = "Total translation",
        ["Sprawdzenie klucza API"] = "API key validation",
        ["Wykluczone dane: klucz API, treść ekranu, wynik OCR i tekst tłumaczenia."] = "Excluded data: API key, screen content, OCR result and translated text.",
        ["brak danych"] = "no data",
        ["tak"] = "yes",
        ["nie"] = "no",
        ["Uzupełnij klucz API oraz oba języki przed uruchomieniem tłumaczenia."] = "Enter the API key and both languages before starting translation.",
        ["Google Translation zwróciło niepełną odpowiedź."] = "Google Translation returned an incomplete response.",
        ["Cloud Translation API odrzuciło zadanie ({0} {1}): {2}"] = "Cloud Translation API rejected the request ({0} {1}): {2}",
        ["Cloud Translation API zwróciło niepełną odpowiedź."] = "Cloud Translation API returned an incomplete response.",
        ["Cloud Vision API odrzuciło zrzut ({0} {1}): {2}"] = "Cloud Vision API rejected the screenshot ({0} {1}): {2}",
        ["Cloud Vision API: {0}"] = "Cloud Vision API: {0}",
        ["Nieznany błąd OCR."] = "Unknown OCR error.",
        ["Nie można zapisać stanu konfiguracji aplikacji."] = "Cannot save app configuration state.",
        ["Nie można zapisać ustawień aplikacji."] = "Cannot save app settings.",
        ["Android Keystore nie zwrócił wektora inicjalizacyjnego."] = "Android Keystore did not return an initialization vector.",
        ["Android Keystore nie zaszyfrował klucza API."] = "Android Keystore did not encrypt the API key.",
        ["Nie można odczytać klucza Android Keystore."] = "Cannot read the Android Keystore key.",
        ["Plik nie zawiera konfiguracji."] = "The file does not contain configuration.",
        ["Ten plik konfiguracji pochodzi z nieobsługiwanej wersji aplikacji."] = "This configuration file comes from an unsupported app version.",
        ["Plik konfiguracji jest niekompletny."] = "The configuration file is incomplete.",
        ["Plik zawiera nieprawidłowe ustawienia OCR lub nakładki."] = "The file contains invalid OCR or overlay settings.",
        ["Plik zawiera nieprawidłowe ustawienia przycisku pływającego."] = "The file contains invalid floating button settings.",
        ["Plik zawiera nieprawidłowy obszar przechwytywania."] = "The file contains an invalid capture region.",
        ["Zgoda na nagrywanie ekranu wygasła. Uruchom tłumacza ponownie i zaakceptuj nowy monit."] = "Screen recording consent expired. Start the translator again and accept the new prompt.",
        ["Nie udało się uruchomić sesji: {0}"] = "Could not start session: {0}",
        ["Nie udzielono zgody na przechwytywanie ekranu."] = "Screen capture permission was not granted.",
        ["Nie udało się uruchomić przechwytywania ekranu."] = "Could not start screen capture.",
        ["Tłumacz jest aktywny."] = "Translator is active.",
        ["Nie można odczytać rozmiaru ekranu."] = "Cannot read screen size.",
        ["Obszar dialogu zapisany."] = "Dialog region saved.",
        ["Przyznaj uprawnienie do wyświetlania nad innymi aplikacjami."] = "Grant permission to display over other apps.",
        ["Nie udało się pobrać klatki ekranu."] = "Could not capture the screen frame.",
        ["Nie udało się zakodować obrazu OCR."] = "Could not encode the OCR image.",
        ["Nie znaleziono tekstu na ekranie."] = "No text found on screen.",
        ["Aktywna sesja tłumacza"] = "Active translator session",
        ["Pikslovo jest aktywne"] = "Pikslovo is active",
        ["Hotkey i przycisk pływający są gotowe."] = "The hotkey and floating button are ready.",
        ["Zatrzymaj"] = "Stop",
    };

    public static AppLanguageMode LanguageMode => _languageMode;

    public static void SetLanguageMode(AppLanguageMode languageMode) => _languageMode = languageMode;

    public static string Get(string value)
    {
        if (UsesPolish || !English.TryGetValue(value, out var translated))
        {
            return value;
        }

        return translated;
    }

    public static string Format(string value, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(value), arguments);

    private static bool UsesPolish => _languageMode switch
    {
        AppLanguageMode.Polish => true,
        AppLanguageMode.English => false,
        _ => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("pl", StringComparison.OrdinalIgnoreCase),
    };
}
