using System.Globalization;
using Pikslovo.Core;

namespace Pikslovo;

public static class AppStrings
{
    public static class Keys
    {
        public const string CheckKey = "Sprawdź klucz";
        public const string Checking = "Sprawdzanie...";
        public const string SourceLanguage = "Język źródłowy";
        public const string TargetLanguage = "Język docelowy";
        public const string MissingApiKeyTitle = "Brak klucza API";
        public const string MissingApiKeyMessage = "Wpisz klucz Google Cloud API, aby go sprawdzić.";
        public const string KeyDoesNotWorkTitle = "Klucz nie działa";
        public const string NoConnectionTitle = "Brak połączenia";
        public const string NoConnectionMessage = "Nie udało się połączyć z Google Cloud. Sprawdź połączenie z Internetem i spróbuj ponownie.";
        public const string TimeoutTitle = "Limit czasu";
        public const string TimeoutMessage = "Sprawdzenie klucza trwało zbyt długo. Spróbuj ponownie przy stabilnym połączeniu.";
        public const string KeyWorksTitle = "Klucz działa";
        public const string KeyWorksMessage = "Klucz ma dostęp do Cloud Translation API i Cloud Vision API.";
        public const string Save = "Zapisz";
        public const string Cancel = "Anuluj";
        public const string Close = "Zamknij";
        public const string Restore = "Przywróć";
        public const string RestoreDefaultsQuestion = "Przywrócić ustawienia domyślne?";
        public const string RestoreDefaultsMessage = "Zostaną zresetowane ustawienia OCR, w tym kompresja JPEG i jakość obrazu, nakładka, obszar przechwytywania oraz przycisk pływający. Klucz API, języki, hotkey i wygląd aplikacji pozostaną bez zmian.";
        public const string AndroidActivityNotReady = "Aktywność Androida nie jest gotowa. Zamknij i otwórz aplikację ponownie.";
        public const string AndroidActivityNotReadyYet = "Aktywność Androida nie jest jeszcze gotowa.";
        public const string TranslatorSessionStopped = "Zatrzymano sesję tłumacza.";
        public const string OpeningScreenSharingDialog = "Otwieram dialog udostępniania ekranu Androida.";
        public const string NotificationPermissionDenied = "Uprawnienie nie zostało przyznane. Możesz spróbować ponownie.";
        public const string SetShortcutOrDisableHotkey = "Ustaw skrót albo wyłącz globalny hotkey.";
        public const string EnterApiKeyAndLanguages = "Wpisz klucz API i wybierz oba języki.";
        public const string SettingsExported = "Ustawienia wyeksportowano do pliku JSON.";
        public const string SettingsImported = "Ustawienia zaimportowano z pliku JSON.";
        public const string DefaultConfigurationRestored = "Przywrócono domyślne ustawienia konfiguracji.";
        public const string OpeningAccessibilitySettings = "Otwieram ustawienia dostępności Androida.";
        public const string NotSet = "Nie ustawiono";
        public const string NoMeasurement = "Brak pomiaru";
        public const string SettingsReadFailed = "Nie można jeszcze odczytać ustawień: {0}";
        public const string OpenGoogleCloudPageFailed = "Nie można otworzyć strony Google Cloud: {0}";
        public const string OpenPikslovoPageFailed = "Nie można otworzyć strony Pikslovo: {0}";
        public const string OpenSupportPageFailed = "Nie można otworzyć strony wsparcia: {0}";
        public const string ApiKeyNoAccess = "Klucz nie ma dostępu do {0}. Sprawdź poprawność klucza oraz czy to API jest włączone w projekcie Google Cloud.";
        public const string ApiKeyCheckFailed = "Nie udało się sprawdzić dostępu do {0}. Usługa Google zwróciła błąd {1}.";
        public const string StartScreenCaptureFailed = "Nie można uruchomić przechwytywania ekranu: {0}";
        public const string ExportDiagnosticsFailed = "Nie można wyeksportować dziennika diagnostycznego: {0}";
        public const string ExportSettingsFailed = "Nie można wyeksportować ustawień: {0}";
        public const string ImportSettingsFailed = "Nie można zaimportować ustawień: {0}";
        public const string OpenFilePickerFailed = "Nie można otworzyć wyboru pliku: {0}";
        public const string RestoreSettingsFailed = "Nie można przywrócić ustawień: {0}";
        public const string OpenOverlaySettingsFailed = "Nie można otworzyć ustawień nakładki: {0}";
        public const string RequestNotificationPermissionFailed = "Nie można poprosić o uprawnienie powiadomień: {0}";
        public const string OpenAccessibilitySettingsFailed = "Nie można otworzyć ustawień dostępności: {0}";
        public const string DiagnosticsReportTitle = "Pikslovo - raport diagnostyczny";
        public const string DiagnosticsGeneratedAtUtc = "Wygenerowano (UTC): {0}";
        public const string DiagnosticsApplication = "Aplikacja: {0}";
        public const string DiagnosticsDevice = "Urządzenie: {0}";
        public const string DiagnosticsActiveSession = "Aktywna sesja tłumacza: {0}";
        public const string DiagnosticsOverlayPermission = "Uprawnienie nakładki: {0}";
        public const string DiagnosticsNotificationPermission = "Uprawnienie powiadomień: {0}";
        public const string DiagnosticsLatestMeasurements = "Ostatnie pomiary:";
        public const string CapturePlusEncoding = "Przechwycenie + kodowanie";
        public const string OcrImageEncoding = "Kodowanie obrazu OCR";
        public const string TotalTranslation = "Całość tłumaczenia";
        public const string ApiKeyValidation = "Sprawdzenie klucza API";
        public const string ThemeSystem = "System";
        public const string ThemeDark = "Ciemny";
        public const string ThemeLight = "Jasny";
        public const string AccentCoral = "Koralowy";
        public const string AccentAmber = "Bursztynowy";
        public const string AccentLime = "Limonkowy";
        public const string AccentMint = "Miętowy";
        public const string AccentTeal = "Morski";
        public const string AccentAqua = "Aqua";
        public const string AccentSky = "Błękitny";
        public const string AccentSteel = "Stalowy";
        public const string AccentOrchid = "Orchidea";
        public const string AccentRose = "Różowy";
        public const string AccentLavender = "Lawendowy";
        public const string LanguageJapanese = "Japoński";
        public const string LanguageEnglish = "Angielski";
        public const string LanguageKorean = "Koreański";
        public const string LanguageChineseSimplified = "Chiński (uproszczony)";
        public const string LanguageGerman = "Niemiecki";
        public const string LanguageSpanish = "Hiszpański";
        public const string LanguagePolish = "Polski";
        public const string UserOcrSettings = "Ustawienia OCR użytkownika:";
        public const string OcrConfidence = "Pewność OCR: {0}";
        public const string OcrImageScale = "Skala obrazu OCR: {0}";
        public const string DialogGroupingStrength = "Siła łączenia dialogów: {0}";
        public const string FontScale = "Skalowanie czcionki: {0}";
        public const string HideIdenticalTranslations = "Ukrywaj identyczne tłumaczenia: {0}";
        public const string OcrImageEncodingFormat = "Kodowanie obrazu OCR: {0}";
        public const string NoData = "brak danych";
        public const string Yes = "tak";
        public const string No = "nie";
        public const string FillApiKeyAndLanguages = "Uzupełnij klucz API oraz oba języki przed uruchomieniem tłumaczenia.";
        public const string GoogleTranslationIncomplete = "Google Translation zwróciło niepełną odpowiedź.";
        public const string CloudTranslationRejected = "Cloud Translation API odrzuciło zadanie ({0} {1}): {2}";
        public const string CloudTranslationIncomplete = "Cloud Translation API zwróciło niepełną odpowiedź.";
        public const string CloudVisionRejected = "Cloud Vision API odrzuciło zrzut ({0} {1}): {2}";
        public const string CloudVisionError = "Cloud Vision API: {0}";
        public const string UnknownOcrError = "Nieznany błąd OCR.";
        public const string CannotSaveSelectedFile = "Nie można zapisać wybranego pliku.";
        public const string CannotReadSelectedFile = "Nie można odczytać wybranego pliku.";
        public const string ShareDiagnostics = "Udostępnij dziennik diagnostyczny";
        public const string CannotOpenSharePanel = "Nie można otworzyć panelu udostępniania.";
        public const string CouldNotStartSession = "Nie udało się uruchomić sesji: {0}";
        public const string CannotReadScreenSize = "Nie można odczytać rozmiaru ekranu.";
        public const string CouldNotEncodeOcrImage = "Nie udało się zakodować obrazu OCR.";
        public const string ActiveTranslatorSession = "Aktywna sesja tłumacza";
        public const string PikslovoIsActive = "Pikslovo jest aktywne";
        public const string HotkeyAndFloatingButtonReady = "Hotkey i przycisk pływający są gotowe.";
        public const string Stop = "Zatrzymaj";
        public const string HoldKeysForTwoSeconds = "Przytrzymaj klawisz(e) przez 2 sekundy";
        public const string SetShortcut = "Ustaw skrót";
        public const string TranslateScreen = "Tłumacz ekran";
        public const string EditCaptureRegion = "Edytuj obszar przechwytywania";
        public const string StopTranslator = "Zatrzymaj tłumacza";
        public const string TranslationInProgress = "Tłumaczenie w toku";
        public const string ReturnToGame = "Wróć do gry";
        public const string DragDialogRegionCorners = "Przeciągnij narożniki obszaru dialogu";
        public const string SaveRegion = "Zapisz obszar";
        public const string CancelRegionSelection = "Anuluj wybór obszaru";
        public const string ConfigurationFileMissing = "Plik nie zawiera konfiguracji.";
        public const string UnsupportedConfigurationVersion = "Ten plik konfiguracji pochodzi z nieobsługiwanej wersji aplikacji.";
        public const string IncompleteConfigurationFile = "Plik konfiguracji jest niekompletny.";
        public const string InvalidOcrOrOverlaySettings = "Plik zawiera nieprawidłowe ustawienia OCR lub nakładki.";
        public const string InvalidFloatingButtonSettings = "Plik zawiera nieprawidłowe ustawienia przycisku pływającego.";
        public const string InvalidCaptureRegion = "Plik zawiera nieprawidłowy obszar przechwytywania.";
        public const string CannotSaveAppConfigurationState = "Nie można zapisać stanu konfiguracji aplikacji.";
        public const string CannotSaveAppSettings = "Nie można zapisać ustawień aplikacji.";
        public const string KeystoreMissingInitializationVector = "Android Keystore nie zwrócił wektora inicjalizacyjnego.";
        public const string KeystoreDidNotEncryptApiKey = "Android Keystore nie zaszyfrował klucza API.";
        public const string CannotReadKeystoreKey = "Nie można odczytać klucza Android Keystore.";
        public const string ScreenCaptureConsentExpired = "Zgoda na nagrywanie ekranu wygasła. Uruchom tłumacza ponownie i zaakceptuj nowy monit.";
        public const string ScreenCaptureConsentDenied = "Nie udzielono zgody na przechwytywanie ekranu.";
        public const string ScreenCaptureStartFailed = "Nie udało się uruchomić przechwytywania ekranu.";
        public const string TranslatorIsActive = "Tłumacz jest aktywny.";
        public const string DialogRegionSaved = "Obszar dialogu zapisany.";
        public const string GrantOverlayPermission = "Przyznaj uprawnienie do wyświetlania nad innymi aplikacjami.";
        public const string ScreenFrameCaptureFailed = "Nie udało się pobrać klatki ekranu.";
        public const string NoTextFoundOnScreen = "Nie znaleziono tekstu na ekranie.";
    }

    private static AppLanguageMode _languageMode = AppLanguageMode.System;

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Tłumacz"] = "Translator",
        ["Wróć do ustawień"] = "Back to settings",
        ["Ustawienia"] = "Settings",
        ["Uprawnienia"] = "Permissions",
        ["Nakładka nad grą i powiadomienia"] = "In-game overlay and notifications",
        ["Klucz do rozpoznawania i tłumaczenia tekstu"] = "Key for text recognition and translation",
        ["Tłumaczenie"] = "Translation",
        ["Języki źródłowy i docelowy"] = "Source and target languages",
        ["Globalny hotkey"] = "Global hotkey",
        ["Skrót do pokazywania tłumaczenia"] = "Shortcut to show the translation",
        ["Przycisk pływający"] = "Floating button",
        ["Widoczność, rozmiar i pozycja na ekranie"] = "Visibility, size and position on screen",
        ["Przetwarzanie tekstu"] = "Text processing",
        ["Pewność OCR, skala obrazu, łączenie dialogów i nakładka"] = "OCR confidence, image scale, dialog grouping and overlay",
        ["Wygląd aplikacji"] = "App appearance",
        ["Konfiguracje"] = "Configurations",
        ["Eksportuj ustawienia"] = "Export settings",
        ["Zapisz OCR, kompresję JPEG, obszar i przycisk do pliku JSON."] = "Save OCR, JPEG compression, region and button settings to a JSON file.",
        ["Importuj ustawienia"] = "Import settings",
        ["Wczytaj OCR, kompresję JPEG i pozostałą konfigurację z pliku JSON."] = "Load OCR, JPEG compression and the remaining configuration from a JSON file.",
        ["Przywróć domyślne"] = "Restore defaults",
        ["Wyczyść OCR wraz z kompresją JPEG, obszarem i przyciskiem."] = "Clear OCR, JPEG compression, region and button settings.",
        ["Wsparcie"] = "Support",
        ["Diagnostyka"] = "Diagnostics",
        ["Ostatnie czasy tłumaczenia i sprawdzenia klucza API"] = "Latest translation and API key validation timings",
        ["GitHub Pikslovo"] = "Pikslovo GitHub",
        ["Kod źródłowy, zgłoszenia błędów i rozwój projektu."] = "Source code, bug reports and project development.",
        ["Wspomóż Pikslovo"] = "Support Pikslovo",
        ["Jeżeli podoba Ci się ta aplikacja, wesprzyj jej dalszy rozwój."] = "If you like this app, support its further development.",
        ["Eksportuj dziennik diagnostyczny"] = "Export diagnostics log",
        ["Zapisz bezpieczny raport z pomiarami, bez klucza API i treści ekranu."] = "Save a safe report with measurements, without the API key or screen content.",
        ["Język źródłowy"] = "Source language",
        ["Język docelowy"] = "Target language",
        ["Klucz jest szyfrowany lokalnie w Android Keystore."] = "The key is encrypted locally in Android Keystore.",
        ["Pokaż lub ukryj klucz API"] = "Show or hide API key",
        ["Uzyskaj klucz Google Cloud API"] = "Get a Google Cloud API key",
        ["Pewność rozpoznawania"] = "Recognition confidence",
        ["Skala obrazu OCR"] = "OCR image scale",
        ["Kompresuj obraz OCR do JPEG"] = "Compress OCR image to JPEG",
        ["Zmniejsza dane wysyłane do Google Cloud."] = "Reduces data sent to Google Cloud.",
        ["Jakość JPEG"] = "JPEG quality",
        ["Siła łączenia tekstu"] = "Text grouping strength",
        ["Skalowanie czcionki"] = "Font scale",
        ["Ukrywaj identyczne tłumaczenia"] = "Hide identical translations",
        ["Nie pokazuj tekstu, gdy tłumaczenie jest takie samo."] = "Do not show text when the translation is identical.",
        ["Ustawienia dostępności"] = "Accessibility settings",
        ["Włącz usługę systemową dla globalnego hotkeya."] = "Enable the system service for the global hotkey.",
        ["Włącz globalny hotkey"] = "Enable global hotkey",
        ["Pozwala wywołać tłumaczenie poza aplikacją."] = "Lets you trigger translation outside the app.",
        ["Klawisz skrótu"] = "Shortcut key",
        ["Zawsze pokazuj przycisk"] = "Always show button",
        ["Rozmiar przycisku"] = "Button size",
        ["Pozycja pozioma"] = "Horizontal position",
        ["Pozycja pionowa"] = "Vertical position",
        ["Nakładka nad grą"] = "In-game overlay",
        ["Zezwól aplikacji wyświetlać tłumaczenie nad innymi aplikacjami."] = "Allow the app to display translations over other apps.",
        ["Powiadomienia"] = "Notifications",
        ["Zezwól na powiadomienie o aktywnej sesji tłumacza."] = "Allow notifications about the active translator session.",
        ["Ostatnie tłumaczenie"] = "Latest translation",
        ["Pomiar jest aktualizowany po zakończeniu tłumaczenia."] = "Measurements are updated when translation completes.",
        ["Przechwycenie + kodowanie"] = "Capture + encoding",
        ["Kodowanie obrazu OCR"] = "OCR image encoding",
        ["Całość"] = "Total",
        ["Ostatnie sprawdzenie klucza API"] = "Latest API key validation",
        ["Motyw"] = "Theme",
        ["System"] = "System",
        ["Ciemny"] = "Dark",
        ["Jasny"] = "Light",
        ["Akcent"] = "Accent",
        ["Język aplikacji"] = "App language",
        ["English"] = "English",
        ["Polski"] = "Polish",
        ["Systemowy"] = "System default",
        ["Koralowy"] = "Coral",
        ["Bursztynowy"] = "Amber",
        ["Limonkowy"] = "Lime",
        ["Miętowy"] = "Mint",
        ["Morski"] = "Teal",
        ["Błękitny"] = "Sky blue",
        ["Stalowy"] = "Steel",
        ["Orchidea"] = "Orchid",
        ["Różowy"] = "Rose",
        ["Lawendowy"] = "Lavender",
        ["Brak pomiaru"] = "No measurement",
        ["Witaj w Pikslovo"] = "Welcome to Pikslovo",
        ["Pikslovo rozpoznaje tekst na ekranie gry i tłumaczy go przez Google Cloud. Zrzut ekranu oraz rozpoznany tekst są wysyłane do usług Google tylko podczas tłumaczenia."] = "Pikslovo recognizes text on your game screen and translates it with Google Cloud. The screenshot and recognized text are sent to Google services only while translating.",
        ["Języki"] = "Languages",
        ["Podczas aktywnej sesji Android wyświetla stałe powiadomienie. Informuje ono, że Pikslovo może przechwytywać ekran na potrzeby tłumaczenia."] = "During an active session, Android displays a persistent notification. It indicates that Pikslovo can capture the screen for translation.",
        ["Widoczna aktywna sesja"] = "Visible active session",
        ["Powiadomienie pozostaje widoczne, gdy tłumacz działa w tle."] = "The notification remains visible while the translator runs in the background.",
        ["Kontrola sesji"] = "Session control",
        ["Z poziomu powiadomienia można zatrzymać aktywną sesję tłumacza."] = "You can stop the active translator session from the notification.",
        ["Pikslovo potrzebuje zgody na wyświetlanie nad innymi aplikacjami, aby pokazać przetłumaczony obraz bez wychodzenia z gry."] = "Pikslovo needs permission to display over other apps so it can show the translated image without leaving the game.",
        ["Tłumaczenie nad grą"] = "Translation over the game",
        ["Wynik pojawi się jako tymczasowa nakładka nad aktualnym ekranem."] = "The result will appear as a temporary overlay over the current screen.",
        ["Tylko na żądanie"] = "Only on demand",
        ["Nakładka jest pokazywana wyłącznie po wywołaniu tłumaczenia."] = "The overlay is shown only after translation is triggered.",
        ["Pikslovo wymaga własnego klucza Google Cloud API do rozpoznawania i tłumaczenia tekstu. Możesz skonfigurować go teraz albo później w ustawieniach. Bez klucza tłumaczenie nie będzie działać."] = "Pikslovo requires your own Google Cloud API key for text recognition and translation. You can configure it now or later in Settings. Translation will not work without it.",
        ["Kontynuuj"] = "Continue",
        ["Przyznaj uprawnienie"] = "Grant permission",
        ["Sprawdź klucz"] = "Check key",
        ["Sprawdzanie..."] = "Checking...",
        ["Nie można jeszcze odczytać ustawień: {0}"] = "Settings cannot be read yet: {0}",
        ["Nie wybrano"] = "Not selected",
        ["Japoński"] = "Japanese",
        ["Angielski"] = "English",
        ["Koreański"] = "Korean",
        ["Chiński (uproszczony)"] = "Chinese (Simplified)",
        ["Niemiecki"] = "German",
        ["Hiszpański"] = "Spanish",
        ["Brak klucza API"] = "Missing API key",
        ["Wpisz klucz Google Cloud API, aby go sprawdzić."] = "Enter a Google Cloud API key to check it.",
        ["Klucz nie działa"] = "Key does not work",
        ["Klucz nie ma dostępu do {0}. Sprawdź poprawność klucza oraz czy to API jest włączone w projekcie Google Cloud."] = "The key cannot access {0}. Check that the key is valid and that this API is enabled in the Google Cloud project.",
        ["Nie udało się sprawdzić dostępu do {0}. Usługa Google zwróciła błąd {1}."] = "Could not check access to {0}. Google returned error {1}.",
        ["Brak połączenia"] = "No connection",
        ["Nie udało się połączyć z Google Cloud. Sprawdź połączenie z Internetem i spróbuj ponownie."] = "Could not connect to Google Cloud. Check your internet connection and try again.",
        ["Limit czasu"] = "Timed out",
        ["Sprawdzenie klucza trwało zbyt długo. Spróbuj ponownie przy stabilnym połączeniu."] = "Key validation took too long. Try again with a stable connection.",
        ["Klucz działa"] = "Key works",
        ["Klucz ma dostęp do Cloud Translation API i Cloud Vision API."] = "The key can access Cloud Translation API and Cloud Vision API.",
        ["Zapisz"] = "Save",
        ["Anuluj"] = "Cancel",
        ["Zamknij"] = "Close",
        ["Przywróć"] = "Restore",
        ["Przywrócić ustawienia domyślne?"] = "Restore default settings?",
        ["Ta operacja wyczyści ustawienia OCR, JPEG, obszaru przechwytywania i przycisku pływającego. Klucz API, języki, hotkey i wygląd aplikacji pozostaną bez zmian."] = "This will clear OCR, JPEG, capture region and floating button settings. The API key, languages, hotkey and app appearance will remain unchanged.",
        ["Zostaną zresetowane ustawienia OCR, w tym kompresja JPEG i jakość obrazu, nakładka, obszar przechwytywania oraz przycisk pływający. Klucz API, języki, hotkey i wygląd aplikacji pozostaną bez zmian."] = "OCR settings, including JPEG compression and image quality, overlay, capture region and floating button will be reset. The API key, languages, hotkey and app appearance will remain unchanged.",
        ["Ustaw skrót"] = "Set shortcut",
        ["Przytrzymaj klawisz(e) przez 2 sekundy"] = "Hold key(s) for 2 seconds",
        ["Nie ustawiono"] = "Not set",
        ["Edytuj obszar przechwytywania"] = "Edit capture region",
        ["Zatrzymaj tłumacza"] = "Stop translator",
        ["Tłumaczenie w toku"] = "Translation in progress",
        ["Wróć do gry"] = "Return to game",
        ["Tłumacz ekran"] = "Translate screen",
        ["Przeciągnij narożniki obszaru dialogu"] = "Drag the dialog region corners",
        ["Zapisz obszar"] = "Save region",
        ["Anuluj wybór obszaru"] = "Cancel region selection",
        ["Udostępnij dziennik diagnostyczny"] = "Share diagnostics log",
        ["Nie można otworzyć panelu udostępniania."] = "Cannot open the share panel.",
        ["Aktywność Androida nie jest gotowa. Zamknij i otwórz aplikację ponownie."] = "Android activity is not ready. Close and reopen the app.",
        ["Aktywność Androida nie jest jeszcze gotowa."] = "Android activity is not ready yet.",
        ["Nie można otworzyć strony Google Cloud: {0}"] = "Cannot open the Google Cloud page: {0}",
        ["Nie można otworzyć strony Pikslovo: {0}"] = "Cannot open the Pikslovo page: {0}",
        ["Nie można otworzyć strony wsparcia: {0}"] = "Cannot open the support page: {0}",
        ["Nie można otworzyć wyboru pliku: {0}"] = "Cannot open the file picker: {0}",
        ["Nie można wyeksportować dziennika diagnostycznego: {0}"] = "Cannot export diagnostics log: {0}",
        ["Przywrócono domyślne ustawienia konfiguracji."] = "Default configuration settings restored.",
        ["Nie można przywrócić ustawień: {0}"] = "Cannot restore settings: {0}",
        ["Uprawnienie nakładki jest już przyznane."] = "Overlay permission is already granted.",
        ["Otwieram ustawienia nakładki Androida."] = "Opening Android overlay settings.",
        ["Nie można otworzyć ustawień nakładki: {0}"] = "Cannot open overlay settings: {0}",
        ["Uprawnienie powiadomień jest już przyznane."] = "Notification permission is already granted.",
        ["Wyświetlam prośbę Androida o zgodę na powiadomienia."] = "Showing Android's notification permission request.",
        ["Nie można poprosić o uprawnienie powiadomień: {0}"] = "Cannot request notification permission: {0}",
        ["Otwieram ustawienia dostępności Androida."] = "Opening Android accessibility settings.",
        ["Nie można otworzyć ustawień dostępności: {0}"] = "Cannot open accessibility settings: {0}",
        ["Zatrzymano sesję tłumacza."] = "Translator session stopped.",
        ["Otwieram dialog udostępniania ekranu Androida."] = "Opening Android's screen sharing dialog.",
        ["Nie można uruchomić przechwytywania ekranu: {0}"] = "Cannot start screen capture: {0}",
        ["Uprawnienie nie zostało przyznane. Możesz spróbować ponownie."] = "Permission was not granted. You can try again.",
        ["Nie można zapisać wybranego pliku."] = "Cannot save the selected file.",
        ["Nie można wyeksportować ustawień: {0}"] = "Cannot export settings: {0}",
        ["Nie można odczytać wybranego pliku."] = "Cannot read the selected file.",
        ["Nie można zaimportować ustawień: {0}"] = "Cannot import settings: {0}",
        ["Ustawienia wyeksportowano do pliku JSON."] = "Settings exported to a JSON file.",
        ["Ustawienia zaimportowano z pliku JSON."] = "Settings imported from a JSON file.",
        ["Ustaw skrót albo wyłącz globalny hotkey."] = "Set a shortcut or disable the global hotkey.",
        ["Wpisz klucz API i wybierz oba języki."] = "Enter an API key and select both languages.",
        ["W aktywnej sesji jest widoczny niezależnie od globalnego hotkeya."] = "It is visible during an active session regardless of the global hotkey.",
        ["W aktywnej sesji jest ukryty, gdy globalny hotkey jest włączony."] = "It is hidden during an active session when the global hotkey is enabled.",
        ["W aktywnej sesji jest widoczny, ponieważ globalny hotkey jest wyłączony."] = "It is visible during an active session because the global hotkey is disabled.",
        ["nieznana"] = "unknown",
        ["Pikslovo - raport diagnostyczny"] = "Pikslovo - diagnostics report",
        ["Wygenerowano (UTC): {0}"] = "Generated (UTC): {0}",
        ["Aplikacja: {0}"] = "Application: {0}",
        ["Urządzenie: {0}"] = "Device: {0}",
        ["Aktywna sesja tłumacza: {0}"] = "Active translator session: {0}",
        ["Uprawnienie nakładki: {0}"] = "Overlay permission: {0}",
        ["Uprawnienie powiadomień: {0}"] = "Notification permission: {0}",
        ["Ostatnie pomiary:"] = "Latest measurements:",
        ["Ustawienia OCR użytkownika:"] = "User OCR settings:",
        ["Pewność OCR: {0}"] = "OCR confidence: {0}",
        ["Skala obrazu OCR: {0}"] = "OCR image scale: {0}",
        ["Siła łączenia dialogów: {0}"] = "Dialog grouping strength: {0}",
        ["Skalowanie czcionki: {0}"] = "Font scale: {0}",
        ["Ukrywaj identyczne tłumaczenia: {0}"] = "Hide identical translations: {0}",
        ["Kodowanie obrazu OCR: {0}"] = "OCR image encoding: {0}",
        ["Całość tłumaczenia"] = "Total translation",
        ["Sprawdzenie klucza API"] = "API key validation",
        ["Wykluczone dane: klucz API, treść ekranu, wynik OCR i tekst tłumaczenia."] = "Excluded data: API key, screen content, OCR result and translated text.",
        ["brak danych"] = "no data",
        ["tak"] = "yes",
        ["nie"] = "no",
        ["Uzupełnij klucz API oraz oba języki przed uruchomieniem tłumaczenia."] = "Enter the API key and both languages before starting translation.",
        ["Google Translation zwróciło niepełną odpowiedź."] = "Google Translation returned an incomplete response.",
        ["Cloud Translation API odrzuciło zadanie ({0} {1}): {2}"] = "Cloud Translation API rejected the request ({0} {1}): {2}",
        ["Cloud Translation API zwróciło niepełną odpowiedź."] = "Cloud Translation API returned an incomplete response.",
        ["Cloud Vision API odrzuciło zrzut ({0} {1}): {2}"] = "Cloud Vision API rejected the screenshot ({0} {1}): {2}",
        ["Cloud Vision API: {0}"] = "Cloud Vision API: {0}",
        ["Nieznany błąd OCR."] = "Unknown OCR error.",
        ["Nie można zapisać stanu konfiguracji aplikacji."] = "Cannot save app configuration state.",
        ["Nie można zapisać ustawień aplikacji."] = "Cannot save app settings.",
        ["Android Keystore nie zwrócił wektora inicjalizacyjnego."] = "Android Keystore did not return an initialization vector.",
        ["Android Keystore nie zaszyfrował klucza API."] = "Android Keystore did not encrypt the API key.",
        ["Nie można odczytać klucza Android Keystore."] = "Cannot read the Android Keystore key.",
        ["Plik nie zawiera konfiguracji."] = "The file does not contain configuration.",
        ["Ten plik konfiguracji pochodzi z nieobsługiwanej wersji aplikacji."] = "This configuration file comes from an unsupported app version.",
        ["Plik konfiguracji jest niekompletny."] = "The configuration file is incomplete.",
        ["Plik zawiera nieprawidłowe ustawienia OCR lub nakładki."] = "The file contains invalid OCR or overlay settings.",
        ["Plik zawiera nieprawidłowe ustawienia przycisku pływającego."] = "The file contains invalid floating button settings.",
        ["Plik zawiera nieprawidłowy obszar przechwytywania."] = "The file contains an invalid capture region.",
        ["Zgoda na nagrywanie ekranu wygasła. Uruchom tłumacza ponownie i zaakceptuj nowy monit."] = "Screen recording consent expired. Start the translator again and accept the new prompt.",
        ["Nie udało się uruchomić sesji: {0}"] = "Could not start session: {0}",
        ["Nie udzielono zgody na przechwytywanie ekranu."] = "Screen capture permission was not granted.",
        ["Nie udało się uruchomić przechwytywania ekranu."] = "Could not start screen capture.",
        ["Tłumacz jest aktywny."] = "Translator is active.",
        ["Nie można odczytać rozmiaru ekranu."] = "Cannot read screen size.",
        ["Obszar dialogu zapisany."] = "Dialog region saved.",
        ["Przyznaj uprawnienie do wyświetlania nad innymi aplikacjami."] = "Grant permission to display over other apps.",
        ["Nie udało się pobrać klatki ekranu."] = "Could not capture the screen frame.",
        ["Nie udało się zakodować obrazu OCR."] = "Could not encode the OCR image.",
        ["Nie znaleziono tekstu na ekranie."] = "No text found on screen.",
        ["Aktywna sesja tłumacza"] = "Active translator session",
        ["Pikslovo jest aktywne"] = "Pikslovo is active",
        ["Hotkey i przycisk pływający są gotowe."] = "The hotkey and floating button are ready.",
        ["Zatrzymaj"] = "Stop",
        ["Zgoda na nagrywanie ekranu wygasła. Uruchom tłumacza ponownie i zaakceptuj nowy monit."] = "Screen recording consent expired. Restart the translator and accept the new prompt.",
        ["Nie udzielono zgody na przechwytywanie ekranu."] = "Screen capture permission was not granted.",
        ["Nie udało się uruchomić przechwytywania ekranu."] = "Could not start screen capture.",
        ["Tłumacz jest aktywny."] = "Translator is active.",
    };

    public static AppLanguageMode LanguageMode => _languageMode;

    public static void SetLanguageMode(AppLanguageMode languageMode) => _languageMode = languageMode;

    public static string Get(string value)
    {
        if (UsesPolish || !English.TryGetValue(value, out var translated))
        {
            return value;
        }

        return translated;
    }

    public static string Format(string value, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(value), arguments);

    public static string GetThemeModeLabel(AppThemeMode mode) => Get(mode switch
    {
        AppThemeMode.Dark => Keys.ThemeDark,
        AppThemeMode.Light => Keys.ThemeLight,
        _ => Keys.ThemeSystem
    });

    public static string GetAccentLabel(AppAccent accent) => Get(accent switch
    {
        AppAccent.Coral => Keys.AccentCoral,
        AppAccent.Amber => Keys.AccentAmber,
        AppAccent.Lime => Keys.AccentLime,
        AppAccent.Mint => Keys.AccentMint,
        AppAccent.Teal => Keys.AccentTeal,
        AppAccent.Aqua => Keys.AccentAqua,
        AppAccent.Sky => Keys.AccentSky,
        AppAccent.Steel => Keys.AccentSteel,
        AppAccent.Orchid => Keys.AccentOrchid,
        AppAccent.Rose => Keys.AccentRose,
        _ => Keys.AccentLavender
    });

    public static string GetLanguageName(string languageCode) => Get(languageCode switch
    {
        "ja" => Keys.LanguageJapanese,
        "en" => Keys.LanguageEnglish,
        "ko" => Keys.LanguageKorean,
        "zh" => Keys.LanguageChineseSimplified,
        "de" => Keys.LanguageGerman,
        "es" => Keys.LanguageSpanish,
        _ => Keys.LanguagePolish
    });

    public static string GetBooleanLabel(bool value) => Get(value ? Keys.Yes : Keys.No);

    private static bool UsesPolish => _languageMode switch
    {
        AppLanguageMode.Polish => true,
        AppLanguageMode.English => false,
        _ => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("pl", StringComparison.OrdinalIgnoreCase),
    };
}
