using System.Globalization;
using Pikslovo.Core;

namespace Pikslovo;

public static class AppStrings
{
    public static class Keys
    {
        public const string CheckKey = nameof(CheckKey);
        public const string Checking = nameof(Checking);
        public const string SourceLanguage = nameof(SourceLanguage);
        public const string TargetLanguage = nameof(TargetLanguage);
        public const string MissingApiKeyTitle = nameof(MissingApiKeyTitle);
        public const string MissingApiKeyMessage = nameof(MissingApiKeyMessage);
        public const string KeyDoesNotWorkTitle = nameof(KeyDoesNotWorkTitle);
        public const string NoConnectionTitle = nameof(NoConnectionTitle);
        public const string NoConnectionMessage = nameof(NoConnectionMessage);
        public const string TimeoutTitle = nameof(TimeoutTitle);
        public const string TimeoutMessage = nameof(TimeoutMessage);
        public const string KeyWorksTitle = nameof(KeyWorksTitle);
        public const string KeyWorksMessage = nameof(KeyWorksMessage);
        public const string Save = nameof(Save);
        public const string Cancel = nameof(Cancel);
        public const string Close = nameof(Close);
        public const string Restore = nameof(Restore);
        public const string RestoreDefaultsQuestion = nameof(RestoreDefaultsQuestion);
        public const string RestoreDefaultsMessage = nameof(RestoreDefaultsMessage);
        public const string AndroidActivityNotReady = nameof(AndroidActivityNotReady);
        public const string AndroidActivityNotReadyYet = nameof(AndroidActivityNotReadyYet);
        public const string TranslatorSessionStopped = nameof(TranslatorSessionStopped);
        public const string OpeningScreenSharingDialog = nameof(OpeningScreenSharingDialog);
        public const string NotificationPermissionDenied = nameof(NotificationPermissionDenied);
        public const string SetShortcutOrDisableHotkey = nameof(SetShortcutOrDisableHotkey);
        public const string EnterApiKeyAndLanguages = nameof(EnterApiKeyAndLanguages);
        public const string SettingsExported = nameof(SettingsExported);
        public const string SettingsImported = nameof(SettingsImported);
        public const string DefaultConfigurationRestored = nameof(DefaultConfigurationRestored);
        public const string OpeningAccessibilitySettings = nameof(OpeningAccessibilitySettings);
        public const string NotSet = nameof(NotSet);
        public const string NoMeasurement = nameof(NoMeasurement);
        public const string SettingsReadFailed = nameof(SettingsReadFailed);
        public const string OpenGoogleCloudPageFailed = nameof(OpenGoogleCloudPageFailed);
        public const string OpenPikslovoPageFailed = nameof(OpenPikslovoPageFailed);
        public const string OpenSupportPageFailed = nameof(OpenSupportPageFailed);
        public const string HotkeyBlockedHelp = nameof(HotkeyBlockedHelp);
        public const string IfShortcutConfigurationIsBlockedOpenThisGuideToUnlockItInAndroid = nameof(IfShortcutConfigurationIsBlockedOpenThisGuideToUnlockItInAndroid);
        public const string AccessibilityPermissionIsAlreadyGranted = nameof(AccessibilityPermissionIsAlreadyGranted);
        public const string ApiKeyNoAccess = nameof(ApiKeyNoAccess);
        public const string ApiKeyCheckFailed = nameof(ApiKeyCheckFailed);
        public const string StartScreenCaptureFailed = nameof(StartScreenCaptureFailed);
        public const string ExportDiagnosticsFailed = nameof(ExportDiagnosticsFailed);
        public const string ExportSettingsFailed = nameof(ExportSettingsFailed);
        public const string ImportSettingsFailed = nameof(ImportSettingsFailed);
        public const string OpenFilePickerFailed = nameof(OpenFilePickerFailed);
        public const string RestoreSettingsFailed = nameof(RestoreSettingsFailed);
        public const string OpenOverlaySettingsFailed = nameof(OpenOverlaySettingsFailed);
        public const string RequestNotificationPermissionFailed = nameof(RequestNotificationPermissionFailed);
        public const string OpenAccessibilitySettingsFailed = nameof(OpenAccessibilitySettingsFailed);
        public const string DiagnosticsReportTitle = nameof(DiagnosticsReportTitle);
        public const string DiagnosticsGeneratedAtUtc = nameof(DiagnosticsGeneratedAtUtc);
        public const string DiagnosticsApplication = nameof(DiagnosticsApplication);
        public const string DiagnosticsDevice = nameof(DiagnosticsDevice);
        public const string DiagnosticsActiveSession = nameof(DiagnosticsActiveSession);
        public const string DiagnosticsOverlayPermission = nameof(DiagnosticsOverlayPermission);
        public const string DiagnosticsNotificationPermission = nameof(DiagnosticsNotificationPermission);
        public const string DiagnosticsLastCaptureAttempt = nameof(DiagnosticsLastCaptureAttempt);
        public const string DiagnosticsLatestMeasurements = nameof(DiagnosticsLatestMeasurements);
        public const string DiagnosticsCaptureStatusSuccess = nameof(DiagnosticsCaptureStatusSuccess);
        public const string DiagnosticsCaptureStatusNoFreshFrame = nameof(DiagnosticsCaptureStatusNoFreshFrame);
        public const string DiagnosticsCaptureStatusFailed = nameof(DiagnosticsCaptureStatusFailed);
        public const string DiagnosticsLatestCapture = nameof(DiagnosticsLatestCapture);
        public const string DiagnosticsLatestCaptureDescription = nameof(DiagnosticsLatestCaptureDescription);
        public const string DiagnosticsCaptureStatusLabel = nameof(DiagnosticsCaptureStatusLabel);
        public const string DiagnosticsCaptureAttemptsLabel = nameof(DiagnosticsCaptureAttemptsLabel);
        public const string DiagnosticsCaptureElapsedLabel = nameof(DiagnosticsCaptureElapsedLabel);
        public const string CapturePlusEncoding = nameof(CapturePlusEncoding);
        public const string OcrImageEncoding = nameof(OcrImageEncoding);
        public const string TotalTranslation = nameof(TotalTranslation);
        public const string ApiKeyValidation = nameof(ApiKeyValidation);
        public const string ThemeSystem = nameof(ThemeSystem);
        public const string ThemeDark = nameof(ThemeDark);
        public const string ThemeLight = nameof(ThemeLight);
        public const string AccentCoral = nameof(AccentCoral);
        public const string AccentAmber = nameof(AccentAmber);
        public const string AccentLime = nameof(AccentLime);
        public const string AccentMint = nameof(AccentMint);
        public const string AccentTeal = nameof(AccentTeal);
        public const string AccentAqua = nameof(AccentAqua);
        public const string AccentSky = nameof(AccentSky);
        public const string AccentSteel = nameof(AccentSteel);
        public const string AccentOrchid = nameof(AccentOrchid);
        public const string AccentRose = nameof(AccentRose);
        public const string AccentLavender = nameof(AccentLavender);
        public const string UserOcrSettings = nameof(UserOcrSettings);
        public const string OcrConfidence = nameof(OcrConfidence);
        public const string OcrImageScale = nameof(OcrImageScale);
        public const string DialogGroupingStrength = nameof(DialogGroupingStrength);
        public const string FontScale = nameof(FontScale);
        public const string HideIdenticalTranslations = nameof(HideIdenticalTranslations);
        public const string OcrImageEncodingFormat = nameof(OcrImageEncodingFormat);
        public const string NoData = nameof(NoData);
        public const string Yes = nameof(Yes);
        public const string No = nameof(No);
        public const string FillApiKeyAndLanguages = nameof(FillApiKeyAndLanguages);
        public const string GoogleTranslationIncomplete = nameof(GoogleTranslationIncomplete);
        public const string CloudTranslationRejected = nameof(CloudTranslationRejected);
        public const string CloudTranslationIncomplete = nameof(CloudTranslationIncomplete);
        public const string CloudVisionRejected = nameof(CloudVisionRejected);
        public const string CloudVisionError = nameof(CloudVisionError);
        public const string UnknownOcrError = nameof(UnknownOcrError);
        public const string CannotSaveSelectedFile = nameof(CannotSaveSelectedFile);
        public const string CannotReadSelectedFile = nameof(CannotReadSelectedFile);
        public const string ShareDiagnostics = nameof(ShareDiagnostics);
        public const string CannotOpenSharePanel = nameof(CannotOpenSharePanel);
        public const string CouldNotStartSession = nameof(CouldNotStartSession);
        public const string CannotReadScreenSize = nameof(CannotReadScreenSize);
        public const string CouldNotEncodeOcrImage = nameof(CouldNotEncodeOcrImage);
        public const string ActiveTranslatorSession = nameof(ActiveTranslatorSession);
        public const string PikslovoIsActive = nameof(PikslovoIsActive);
        public const string HotkeyAndFloatingButtonReady = nameof(HotkeyAndFloatingButtonReady);
        public const string Stop = nameof(Stop);
        public const string HoldKeysForTwoSeconds = nameof(HoldKeysForTwoSeconds);
        public const string SetShortcut = nameof(SetShortcut);
        public const string TapToSetShortcut = nameof(TapToSetShortcut);
        public const string TranslateScreen = nameof(TranslateScreen);
        public const string EditCaptureRegion = nameof(EditCaptureRegion);
        public const string StopTranslator = nameof(StopTranslator);
        public const string TranslationInProgress = nameof(TranslationInProgress);
        public const string ReturnToGame = nameof(ReturnToGame);
        public const string DragDialogRegionCorners = nameof(DragDialogRegionCorners);
        public const string SaveRegion = nameof(SaveRegion);
        public const string CancelRegionSelection = nameof(CancelRegionSelection);
        public const string RestoreFullScreenRegion = nameof(RestoreFullScreenRegion);
        public const string ConfigurationFileMissing = nameof(ConfigurationFileMissing);
        public const string UnsupportedConfigurationVersion = nameof(UnsupportedConfigurationVersion);
        public const string IncompleteConfigurationFile = nameof(IncompleteConfigurationFile);
        public const string InvalidOcrOrOverlaySettings = nameof(InvalidOcrOrOverlaySettings);
        public const string InvalidFloatingButtonSettings = nameof(InvalidFloatingButtonSettings);
        public const string InvalidCaptureRegion = nameof(InvalidCaptureRegion);
        public const string CannotSaveAppConfigurationState = nameof(CannotSaveAppConfigurationState);
        public const string CannotSaveAppSettings = nameof(CannotSaveAppSettings);
        public const string KeystoreMissingInitializationVector = nameof(KeystoreMissingInitializationVector);
        public const string KeystoreDidNotEncryptApiKey = nameof(KeystoreDidNotEncryptApiKey);
        public const string CannotReadKeystoreKey = nameof(CannotReadKeystoreKey);
        public const string ScreenCaptureConsentExpired = nameof(ScreenCaptureConsentExpired);
        public const string ScreenCaptureConsentDenied = nameof(ScreenCaptureConsentDenied);
        public const string ScreenCaptureStartFailed = nameof(ScreenCaptureStartFailed);
        public const string TranslatorIsActive = nameof(TranslatorIsActive);
        public const string DialogRegionSaved = nameof(DialogRegionSaved);
        public const string GrantOverlayPermission = nameof(GrantOverlayPermission);
        public const string ScreenFrameCaptureFailed = nameof(ScreenFrameCaptureFailed);
        public const string NoTextFoundOnScreen = nameof(NoTextFoundOnScreen);
        public const string Translator = nameof(Translator);
        public const string BackToSettings = nameof(BackToSettings);
        public const string Settings = nameof(Settings);
        public const string Permissions = nameof(Permissions);
        public const string InGameOverlayAndNotifications = nameof(InGameOverlayAndNotifications);
        public const string KeyForTextRecognitionAndTranslation = nameof(KeyForTextRecognitionAndTranslation);
        public const string Translation = nameof(Translation);
        public const string SourceAndTargetLanguages = nameof(SourceAndTargetLanguages);
        public const string GlobalHotkey = nameof(GlobalHotkey);
        public const string ShortcutToShowTheTranslation = nameof(ShortcutToShowTheTranslation);
        public const string FloatingButton = nameof(FloatingButton);
        public const string VisibilitySizeAndPositionOnScreen = nameof(VisibilitySizeAndPositionOnScreen);
        public const string TextProcessing = nameof(TextProcessing);
        public const string OcrConfidenceImageScaleDialogGroupingAndOverlay = nameof(OcrConfidenceImageScaleDialogGroupingAndOverlay);
        public const string AppAppearance = nameof(AppAppearance);
        public const string Configurations = nameof(Configurations);
        public const string ExportSettings = nameof(ExportSettings);
        public const string SaveOcrJpegCompressionRegionAndButtonSettingsToAJsonFile = nameof(SaveOcrJpegCompressionRegionAndButtonSettingsToAJsonFile);
        public const string ImportSettings = nameof(ImportSettings);
        public const string LoadOcrJpegCompressionAndTheRemainingConfigurationFromAJsonFile = nameof(LoadOcrJpegCompressionAndTheRemainingConfigurationFromAJsonFile);
        public const string RestoreDefaults = nameof(RestoreDefaults);
        public const string ClearOcrJpegCompressionRegionAndButtonSettings = nameof(ClearOcrJpegCompressionRegionAndButtonSettings);
        public const string Support = nameof(Support);
        public const string Diagnostics = nameof(Diagnostics);
        public const string LatestTranslationAndApiKeyValidationTimings = nameof(LatestTranslationAndApiKeyValidationTimings);
        public const string PikslovoGitHub = nameof(PikslovoGitHub);
        public const string SourceCodeBugReportsAndProjectDevelopment = nameof(SourceCodeBugReportsAndProjectDevelopment);
        public const string SupportPikslovo = nameof(SupportPikslovo);
        public const string IfYouLikeThisAppSupportItsFurtherDevelopment = nameof(IfYouLikeThisAppSupportItsFurtherDevelopment);
        public const string ExportDiagnosticsLog = nameof(ExportDiagnosticsLog);
        public const string SaveASafeReportWithMeasurementsWithoutTheApiKeyOrScreenContent = nameof(SaveASafeReportWithMeasurementsWithoutTheApiKeyOrScreenContent);
        public const string ImportantNeverShareThisKeyWithAnyone = nameof(ImportantNeverShareThisKeyWithAnyone);
        public const string ShowOrHideApiKey = nameof(ShowOrHideApiKey);
        public const string GetAGoogleCloudApiKey = nameof(GetAGoogleCloudApiKey);
        public const string GoogleCloudApiKeySetupGuide = nameof(GoogleCloudApiKeySetupGuide);
        public const string OpenStepByStepInstructionsForCreatingAnApiKey = nameof(OpenStepByStepInstructionsForCreatingAnApiKey);
        public const string RecognitionConfidence = nameof(RecognitionConfidence);
        public const string OcrImageScaleSetting = nameof(OcrImageScaleSetting);
        public const string CompressOcrImageToJpeg = nameof(CompressOcrImageToJpeg);
        public const string ReducesDataSentToGoogleCloud = nameof(ReducesDataSentToGoogleCloud);
        public const string JpegQuality = nameof(JpegQuality);
        public const string TextGroupingStrength = nameof(TextGroupingStrength);
        public const string FontScaleSetting = nameof(FontScaleSetting);
        public const string HideIdenticalTranslationsSetting = nameof(HideIdenticalTranslationsSetting);
        public const string DoNotShowTextWhenTheTranslationIsIdentical = nameof(DoNotShowTextWhenTheTranslationIsIdentical);
        public const string AccessibilitySettings = nameof(AccessibilitySettings);
        public const string EnableTheSystemServiceForTheGlobalHotkey = nameof(EnableTheSystemServiceForTheGlobalHotkey);
        public const string EnableGlobalHotkey = nameof(EnableGlobalHotkey);
        public const string LetsYouTriggerTranslationOutsideTheApp = nameof(LetsYouTriggerTranslationOutsideTheApp);
        public const string ShortcutKey = nameof(ShortcutKey);
        public const string AlwaysShowButton = nameof(AlwaysShowButton);
        public const string ButtonSize = nameof(ButtonSize);
        public const string HorizontalPosition = nameof(HorizontalPosition);
        public const string VerticalPosition = nameof(VerticalPosition);
        public const string InGameOverlay = nameof(InGameOverlay);
        public const string AllowTheAppToDisplayTranslationsOverOtherApps = nameof(AllowTheAppToDisplayTranslationsOverOtherApps);
        public const string NotificationsSection = nameof(NotificationsSection);
        public const string AllowNotificationsAboutTheActiveTranslatorSession = nameof(AllowNotificationsAboutTheActiveTranslatorSession);
        public const string LatestTranslation = nameof(LatestTranslation);
        public const string MeasurementsAreUpdatedWhenTranslationCompletes = nameof(MeasurementsAreUpdatedWhenTranslationCompletes);
        public const string TotalSummary = nameof(TotalSummary);
        public const string LatestApiKeyValidation = nameof(LatestApiKeyValidation);
        public const string ThemeSection = nameof(ThemeSection);
        public const string AccentSection = nameof(AccentSection);
        public const string AppLanguage = nameof(AppLanguage);
        public const string English = nameof(English);
        public const string Polish = nameof(Polish);
        public const string SystemDefault = nameof(SystemDefault);
        public const string WelcomeToPikslovo = nameof(WelcomeToPikslovo);
        public const string PikslovoRecognizesTextOnYourGameScreenAndTranslatesItWithGoogleCloudTheScreenshotAndRecognizedTextAreSentToGoogleServicesOnlyWhileTranslating = nameof(PikslovoRecognizesTextOnYourGameScreenAndTranslatesItWithGoogleCloudTheScreenshotAndRecognizedTextAreSentToGoogleServicesOnlyWhileTranslating);
        public const string Languages = nameof(Languages);
        public const string DuringAnActiveSessionAndroidDisplaysAPersistentNotificationItIndicatesThatPikslovoCanCaptureTheScreenForTranslation = nameof(DuringAnActiveSessionAndroidDisplaysAPersistentNotificationItIndicatesThatPikslovoCanCaptureTheScreenForTranslation);
        public const string VisibleActiveSession = nameof(VisibleActiveSession);
        public const string TheNotificationRemainsVisibleWhileTheTranslatorRunsInTheBackground = nameof(TheNotificationRemainsVisibleWhileTheTranslatorRunsInTheBackground);
        public const string SessionControl = nameof(SessionControl);
        public const string YouCanStopTheActiveTranslatorSessionFromTheNotification = nameof(YouCanStopTheActiveTranslatorSessionFromTheNotification);
        public const string PikslovoNeedsPermissionToDisplayOverOtherAppsSoItCanShowTheTranslatedImageWithoutLeavingTheGame = nameof(PikslovoNeedsPermissionToDisplayOverOtherAppsSoItCanShowTheTranslatedImageWithoutLeavingTheGame);
        public const string TranslationOverTheGame = nameof(TranslationOverTheGame);
        public const string TheResultWillAppearAsATemporaryOverlayOverTheCurrentScreen = nameof(TheResultWillAppearAsATemporaryOverlayOverTheCurrentScreen);
        public const string OnlyOnDemand = nameof(OnlyOnDemand);
        public const string TheOverlayIsShownOnlyAfterTranslationIsTriggered = nameof(TheOverlayIsShownOnlyAfterTranslationIsTriggered);
        public const string PikslovoRequiresYourOwnGoogleCloudApiKeyForTextRecognitionAndTranslationYouCanConfigureItNowOrLaterInSettingsTranslationWillNotWorkWithoutIt = nameof(PikslovoRequiresYourOwnGoogleCloudApiKeyForTextRecognitionAndTranslationYouCanConfigureItNowOrLaterInSettingsTranslationWillNotWorkWithoutIt);
        public const string Continue = nameof(Continue);
        public const string GrantPermission = nameof(GrantPermission);
        public const string NotSelected = nameof(NotSelected);
        public const string ThisWillClearOcrJpegCaptureRegionAndFloatingButtonSettingsTheApiKeyLanguagesHotkeyAndAppAppearanceWillRemainUnchanged = nameof(ThisWillClearOcrJpegCaptureRegionAndFloatingButtonSettingsTheApiKeyLanguagesHotkeyAndAppAppearanceWillRemainUnchanged);
        public const string OverlayPermissionIsAlreadyGranted = nameof(OverlayPermissionIsAlreadyGranted);
        public const string OpeningAndroidOverlaySettings = nameof(OpeningAndroidOverlaySettings);
        public const string NotificationPermissionIsAlreadyGranted = nameof(NotificationPermissionIsAlreadyGranted);
        public const string ShowingAndroidNotificationPermissionRequest = nameof(ShowingAndroidNotificationPermissionRequest);
        public const string ItIsVisibleDuringAnActiveSessionRegardlessOfTheGlobalHotkey = nameof(ItIsVisibleDuringAnActiveSessionRegardlessOfTheGlobalHotkey);
        public const string ItIsHiddenDuringAnActiveSessionWhenTheGlobalHotkeyIsEnabled = nameof(ItIsHiddenDuringAnActiveSessionWhenTheGlobalHotkeyIsEnabled);
        public const string ItIsVisibleDuringAnActiveSessionBecauseTheGlobalHotkeyIsDisabled = nameof(ItIsVisibleDuringAnActiveSessionBecauseTheGlobalHotkeyIsDisabled);
        public const string Unknown = nameof(Unknown);
        public const string ExcludedDataApiKeyScreenContentOcrResultAndTranslatedText = nameof(ExcludedDataApiKeyScreenContentOcrResultAndTranslatedText);
        public const string GoogleCloudApi = nameof(GoogleCloudApi);
        public const string GoogleCloudApiKey = nameof(GoogleCloudApiKey);
        public const string OcrImageSize = nameof(OcrImageSize);
        public const string CloudVisionOcrLabel = nameof(CloudVisionOcrLabel);
        public const string CloudTranslationLabel = nameof(CloudTranslationLabel);
        public const string OverlayRender = nameof(OverlayRender);
    }

    private static AppLanguageMode _languageMode = AppLanguageMode.System;

    private static readonly IReadOnlyDictionary<string, string> Polish = new Dictionary<string, string>
    {
        [Keys.CheckKey] = "Sprawdź klucz",
        [Keys.Checking] = "Sprawdzanie...",
        [Keys.SourceLanguage] = "Język źródłowy",
        [Keys.TargetLanguage] = "Język docelowy",
        [Keys.MissingApiKeyTitle] = "Brak klucza API",
        [Keys.MissingApiKeyMessage] = "Wpisz klucz Google Cloud API, aby go sprawdzić.",
        [Keys.KeyDoesNotWorkTitle] = "Klucz nie działa",
        [Keys.NoConnectionTitle] = "Brak połączenia",
        [Keys.NoConnectionMessage] = "Nie udało się połączyć z Google Cloud. Sprawdź połączenie z Internetem i spróbuj ponownie.",
        [Keys.TimeoutTitle] = "Limit czasu",
        [Keys.TimeoutMessage] = "Sprawdzenie klucza trwało zbyt długo. Spróbuj ponownie przy stabilnym połączeniu.",
        [Keys.KeyWorksTitle] = "Klucz działa",
        [Keys.KeyWorksMessage] = "Klucz ma dostęp do Cloud Translation API i Cloud Vision API.",
        [Keys.Save] = "Zapisz",
        [Keys.Cancel] = "Anuluj",
        [Keys.Close] = "Zamknij",
        [Keys.Restore] = "Przywróć",
        [Keys.RestoreDefaultsQuestion] = "Przywrócić ustawienia domyślne?",
        [Keys.RestoreDefaultsMessage] = "Zostaną zresetowane ustawienia OCR, w tym kompresja JPEG i jakość obrazu, nakładka, obszar przechwytywania oraz przycisk pływający. Klucz API, języki, globalny skrót i wygląd aplikacji pozostaną bez zmian.",
        [Keys.AndroidActivityNotReady] = "Aktywność Androida nie jest gotowa. Zamknij i otwórz aplikację ponownie.",
        [Keys.AndroidActivityNotReadyYet] = "Aktywność Androida nie jest jeszcze gotowa.",
        [Keys.TranslatorSessionStopped] = "Zatrzymano sesję tłumacza.",
        [Keys.OpeningScreenSharingDialog] = "Otwieram dialog udostępniania ekranu Androida.",
        [Keys.NotificationPermissionDenied] = "Uprawnienie nie zostało przyznane. Możesz spróbować ponownie.",
        [Keys.SetShortcutOrDisableHotkey] = "Ustaw skrót albo wyłącz globalny skrót.",
        [Keys.EnterApiKeyAndLanguages] = "Wpisz klucz API i wybierz oba języki.",
        [Keys.SettingsExported] = "Ustawienia wyeksportowano do pliku JSON.",
        [Keys.SettingsImported] = "Ustawienia zaimportowano z pliku JSON.",
        [Keys.DefaultConfigurationRestored] = "Przywrócono domyślne ustawienia konfiguracji.",
        [Keys.OpeningAccessibilitySettings] = "Otwieram ustawienia dostępności Androida.",
        [Keys.NotSet] = "Nie ustawiono",
        [Keys.NoMeasurement] = "Brak pomiaru",
        [Keys.SettingsReadFailed] = "Nie można jeszcze odczytać ustawień: {0}",
        [Keys.OpenGoogleCloudPageFailed] = "Nie można otworzyć strony Google Cloud: {0}",
        [Keys.OpenPikslovoPageFailed] = "Nie można otworzyć strony Pikslovo: {0}",
        [Keys.OpenSupportPageFailed] = "Nie można otworzyć strony wsparcia: {0}",
        [Keys.HotkeyBlockedHelp] = "Jak odblokować ustawienie skrótu",
        [Keys.IfShortcutConfigurationIsBlockedOpenThisGuideToUnlockItInAndroid] = "Jeżeli opcja ustawienia skrótu jest zablokowana, pod tym linkiem znajdziesz instrukcję, jak odblokować ją w Androidzie.",
        [Keys.AccessibilityPermissionIsAlreadyGranted] = "Uprawnienie dostępności jest już przyznane.",
        [Keys.ApiKeyNoAccess] = "Klucz nie ma dostępu do {0}. Sprawdź poprawność klucza oraz czy to API jest włączone w projekcie Google Cloud.",
        [Keys.ApiKeyCheckFailed] = "Nie udało się sprawdzić dostępu do {0}. Usługa Google zwróciła błąd {1}.",
        [Keys.StartScreenCaptureFailed] = "Nie można uruchomić przechwytywania ekranu: {0}",
        [Keys.ExportDiagnosticsFailed] = "Nie można wyeksportować dziennika diagnostycznego: {0}",
        [Keys.ExportSettingsFailed] = "Nie można wyeksportować ustawień: {0}",
        [Keys.ImportSettingsFailed] = "Nie można zaimportować ustawień: {0}",
        [Keys.OpenFilePickerFailed] = "Nie można otworzyć wyboru pliku: {0}",
        [Keys.RestoreSettingsFailed] = "Nie można przywrócić ustawień: {0}",
        [Keys.OpenOverlaySettingsFailed] = "Nie można otworzyć ustawień nakładki: {0}",
        [Keys.RequestNotificationPermissionFailed] = "Nie można poprosić o uprawnienie powiadomień: {0}",
        [Keys.OpenAccessibilitySettingsFailed] = "Nie można otworzyć ustawień dostępności: {0}",
        [Keys.DiagnosticsReportTitle] = "Pikslovo - raport diagnostyczny",
        [Keys.DiagnosticsGeneratedAtUtc] = "Wygenerowano (UTC): {0}",
        [Keys.DiagnosticsApplication] = "Aplikacja: {0}",
        [Keys.DiagnosticsDevice] = "Urządzenie: {0}",
        [Keys.DiagnosticsActiveSession] = "Aktywna sesja tłumacza: {0}",
        [Keys.DiagnosticsOverlayPermission] = "Uprawnienie nakładki: {0}",
        [Keys.DiagnosticsNotificationPermission] = "Uprawnienie powiadomień: {0}",
        [Keys.DiagnosticsLastCaptureAttempt] = "Ostatnia próba przechwycenia: status={0}, próby={1}, czas={2}",
        [Keys.DiagnosticsLatestMeasurements] = "Ostatnie pomiary:",
        [Keys.DiagnosticsCaptureStatusSuccess] = "sukces",
        [Keys.DiagnosticsCaptureStatusNoFreshFrame] = "brak świeżej klatki",
        [Keys.DiagnosticsCaptureStatusFailed] = "błąd odczytu",
        [Keys.DiagnosticsLatestCapture] = "Ostatnie przechwycenie",
        [Keys.DiagnosticsLatestCaptureDescription] = "Status ostatniej próby pobrania klatki z sesji MediaProjection.",
        [Keys.DiagnosticsCaptureStatusLabel] = "Status",
        [Keys.DiagnosticsCaptureAttemptsLabel] = "Próby",
        [Keys.DiagnosticsCaptureElapsedLabel] = "Czas oczekiwania",
        [Keys.CapturePlusEncoding] = "Przechwycenie + kodowanie",
        [Keys.OcrImageEncoding] = "Kodowanie obrazu OCR",
        [Keys.TotalTranslation] = "Całość tłumaczenia",
        [Keys.ApiKeyValidation] = "Sprawdzenie klucza API",
        [Keys.ThemeSystem] = "System",
        [Keys.ThemeDark] = "Ciemny",
        [Keys.ThemeLight] = "Jasny",
        [Keys.AccentCoral] = "Koralowy",
        [Keys.AccentAmber] = "Bursztynowy",
        [Keys.AccentLime] = "Limonkowy",
        [Keys.AccentMint] = "Miętowy",
        [Keys.AccentTeal] = "Morski",
        [Keys.AccentAqua] = "Aqua",
        [Keys.AccentSky] = "Błękitny",
        [Keys.AccentSteel] = "Stalowy",
        [Keys.AccentOrchid] = "Orchidea",
        [Keys.AccentRose] = "Różowy",
        [Keys.AccentLavender] = "Lawendowy",
        [Keys.UserOcrSettings] = "Ustawienia OCR użytkownika:",
        [Keys.OcrConfidence] = "Pewność OCR: {0}",
        [Keys.OcrImageScale] = "Skala obrazu OCR: {0}",
        [Keys.DialogGroupingStrength] = "Siła łączenia dialogów: {0}",
        [Keys.FontScale] = "Skalowanie czcionki: {0}",
        [Keys.HideIdenticalTranslations] = "Ukrywaj identyczne tłumaczenia: {0}",
        [Keys.OcrImageEncodingFormat] = "Kodowanie obrazu OCR: {0}",
        [Keys.NoData] = "brak danych",
        [Keys.Yes] = "tak",
        [Keys.No] = "nie",
        [Keys.FillApiKeyAndLanguages] = "Uzupełnij klucz API oraz oba języki przed uruchomieniem tłumaczenia.",
        [Keys.GoogleTranslationIncomplete] = "Google Translation zwróciło niepełną odpowiedź.",
        [Keys.CloudTranslationRejected] = "Cloud Translation API odrzuciło zadanie ({0} {1}): {2}",
        [Keys.CloudTranslationIncomplete] = "Cloud Translation API zwróciło niepełną odpowiedź.",
        [Keys.CloudVisionRejected] = "Cloud Vision API odrzuciło zrzut ({0} {1}): {2}",
        [Keys.CloudVisionError] = "Cloud Vision API: {0}",
        [Keys.UnknownOcrError] = "Nieznany błąd OCR.",
        [Keys.CannotSaveSelectedFile] = "Nie można zapisać wybranego pliku.",
        [Keys.CannotReadSelectedFile] = "Nie można odczytać wybranego pliku.",
        [Keys.ShareDiagnostics] = "Udostępnij dziennik diagnostyczny",
        [Keys.CannotOpenSharePanel] = "Nie można otworzyć panelu udostępniania.",
        [Keys.CouldNotStartSession] = "Nie udało się uruchomić sesji: {0}",
        [Keys.CannotReadScreenSize] = "Nie można odczytać rozmiaru ekranu.",
        [Keys.CouldNotEncodeOcrImage] = "Nie udało się zakodować obrazu OCR.",
        [Keys.ActiveTranslatorSession] = "Aktywna sesja tłumacza",
        [Keys.PikslovoIsActive] = "Pikslovo jest aktywne",
        [Keys.HotkeyAndFloatingButtonReady] = "Globalny skrót i przycisk pływający są gotowe.",
        [Keys.Stop] = "Zatrzymaj",
        [Keys.HoldKeysForTwoSeconds] = "Przytrzymaj klawisz(e) przez 1 sekundę",
        [Keys.SetShortcut] = "Ustaw skrót",
        [Keys.TapToSetShortcut] = "Dotknij, aby ustawić skrót",
        [Keys.TranslateScreen] = "Tłumacz ekran",
        [Keys.EditCaptureRegion] = "Edytuj obszar przechwytywania",
        [Keys.StopTranslator] = "Zatrzymaj tłumacza",
        [Keys.TranslationInProgress] = "Tłumaczenie w toku",
        [Keys.ReturnToGame] = "Wróć do gry",
        [Keys.DragDialogRegionCorners] = "Przeciągnij narożniki obszaru dialogu",
        [Keys.SaveRegion] = "Zapisz obszar",
        [Keys.CancelRegionSelection] = "Anuluj wybór obszaru",
        [Keys.RestoreFullScreenRegion] = "Przywróć pełny ekran",
        [Keys.ConfigurationFileMissing] = "Plik nie zawiera konfiguracji.",
        [Keys.UnsupportedConfigurationVersion] = "Ten plik konfiguracji pochodzi z nieobsługiwanej wersji aplikacji.",
        [Keys.IncompleteConfigurationFile] = "Plik konfiguracji jest niekompletny.",
        [Keys.InvalidOcrOrOverlaySettings] = "Plik zawiera nieprawidłowe ustawienia OCR lub nakładki.",
        [Keys.InvalidFloatingButtonSettings] = "Plik zawiera nieprawidłowe ustawienia przycisku pływającego.",
        [Keys.InvalidCaptureRegion] = "Plik zawiera nieprawidłowy obszar przechwytywania.",
        [Keys.CannotSaveAppConfigurationState] = "Nie można zapisać stanu konfiguracji aplikacji.",
        [Keys.CannotSaveAppSettings] = "Nie można zapisać ustawień aplikacji.",
        [Keys.KeystoreMissingInitializationVector] = "Android Keystore nie zwrócił wektora inicjalizacyjnego.",
        [Keys.KeystoreDidNotEncryptApiKey] = "Android Keystore nie zaszyfrował klucza API.",
        [Keys.CannotReadKeystoreKey] = "Nie można odczytać klucza Android Keystore.",
        [Keys.ScreenCaptureConsentExpired] = "Zgoda na nagrywanie ekranu wygasła. Uruchom tłumacza ponownie i zaakceptuj nowy monit.",
        [Keys.ScreenCaptureConsentDenied] = "Nie udzielono zgody na przechwytywanie ekranu.",
        [Keys.ScreenCaptureStartFailed] = "Nie udało się uruchomić przechwytywania ekranu.",
        [Keys.TranslatorIsActive] = "Tłumacz jest aktywny.",
        [Keys.DialogRegionSaved] = "Obszar dialogu zapisany.",
        [Keys.GrantOverlayPermission] = "Przyznaj uprawnienie do wyświetlania nad innymi aplikacjami.",
        [Keys.ScreenFrameCaptureFailed] = "Nie udało się pobrać klatki ekranu.",
        [Keys.NoTextFoundOnScreen] = "Nie znaleziono tekstu na ekranie.",
        [Keys.Translator] = "Tłumacz",
        [Keys.BackToSettings] = "Wróć do ustawień",
        [Keys.Settings] = "Ustawienia",
        [Keys.Permissions] = "Uprawnienia",
        [Keys.InGameOverlayAndNotifications] = "Nakładka nad grą i powiadomienia",
        [Keys.KeyForTextRecognitionAndTranslation] = "Klucz do rozpoznawania i tłumaczenia tekstu",
        [Keys.Translation] = "Tłumaczenie",
        [Keys.SourceAndTargetLanguages] = "Języki źródłowy i docelowy",
        [Keys.GlobalHotkey] = "Globalny skrót",
        [Keys.ShortcutToShowTheTranslation] = "Skrót do pokazywania tłumaczenia",
        [Keys.FloatingButton] = "Przycisk pływający",
        [Keys.VisibilitySizeAndPositionOnScreen] = "Widoczność, rozmiar i pozycja na ekranie",
        [Keys.TextProcessing] = "Przetwarzanie tekstu",
        [Keys.OcrConfidenceImageScaleDialogGroupingAndOverlay] = "Pewność OCR, skala obrazu, łączenie dialogów i nakładka",
        [Keys.AppAppearance] = "Wygląd aplikacji",
        [Keys.Configurations] = "Konfiguracje",
        [Keys.ExportSettings] = "Eksportuj ustawienia",
        [Keys.SaveOcrJpegCompressionRegionAndButtonSettingsToAJsonFile] = "Zapisz OCR, kompresję JPEG, obszar i przycisk do pliku JSON.",
        [Keys.ImportSettings] = "Importuj ustawienia",
        [Keys.LoadOcrJpegCompressionAndTheRemainingConfigurationFromAJsonFile] = "Wczytaj OCR, kompresję JPEG i pozostałą konfigurację z pliku JSON.",
        [Keys.RestoreDefaults] = "Przywróć domyślne",
        [Keys.ClearOcrJpegCompressionRegionAndButtonSettings] = "Wyczyść OCR wraz z kompresją JPEG, obszarem i przyciskiem.",
        [Keys.Support] = "Wsparcie",
        [Keys.Diagnostics] = "Diagnostyka",
        [Keys.LatestTranslationAndApiKeyValidationTimings] = "Ostatnie czasy tłumaczenia i sprawdzenia klucza API",
        [Keys.PikslovoGitHub] = "GitHub Pikslovo",
        [Keys.SourceCodeBugReportsAndProjectDevelopment] = "Kod źródłowy, zgłoszenia błędów i rozwój projektu.",
        [Keys.SupportPikslovo] = "Wspomóż Pikslovo",
        [Keys.IfYouLikeThisAppSupportItsFurtherDevelopment] = "Jeżeli podoba Ci się ta aplikacja, wesprzyj jej dalszy rozwój.",
        [Keys.ExportDiagnosticsLog] = "Eksportuj dziennik diagnostyczny",
        [Keys.SaveASafeReportWithMeasurementsWithoutTheApiKeyOrScreenContent] = "Zapisz bezpieczny raport z pomiarami, bez klucza API i treści ekranu.",
        [Keys.ImportantNeverShareThisKeyWithAnyone] = "Ważne: nigdy nie udostępniaj tego klucza nikomu.",
        [Keys.ShowOrHideApiKey] = "Pokaż lub ukryj klucz API",
        [Keys.GetAGoogleCloudApiKey] = "Uzyskaj klucz Google Cloud API",
        [Keys.GoogleCloudApiKeySetupGuide] = "Instrukcja uzyskania klucza API",
        [Keys.OpenStepByStepInstructionsForCreatingAnApiKey] = "Otwórz instrukcję krok po kroku tworzenia klucza Google Cloud API.",
        [Keys.RecognitionConfidence] = "Pewność rozpoznawania",
        [Keys.OcrImageScaleSetting] = "Skala obrazu OCR",
        [Keys.CompressOcrImageToJpeg] = "Kompresuj obraz OCR do JPEG",
        [Keys.ReducesDataSentToGoogleCloud] = "Zmniejsza dane wysyłane do Google Cloud.",
        [Keys.JpegQuality] = "Jakość JPEG",
        [Keys.TextGroupingStrength] = "Siła łączenia tekstu",
        [Keys.FontScaleSetting] = "Skalowanie czcionki",
        [Keys.HideIdenticalTranslationsSetting] = "Ukrywaj identyczne tłumaczenia",
        [Keys.DoNotShowTextWhenTheTranslationIsIdentical] = "Nie pokazuj tekstu, gdy tłumaczenie jest takie samo.",
        [Keys.AccessibilitySettings] = "Ustawienia dostępności",
        [Keys.EnableTheSystemServiceForTheGlobalHotkey] = "Włącz usługę systemową dla globalnego skrótu.",
        [Keys.EnableGlobalHotkey] = "Włącz globalny skrót",
        [Keys.LetsYouTriggerTranslationOutsideTheApp] = "Pozwala wywołać tłumaczenie poza aplikacją.",
        [Keys.ShortcutKey] = "Skrót",
        [Keys.AlwaysShowButton] = "Zawsze pokazuj przycisk",
        [Keys.ButtonSize] = "Rozmiar przycisku",
        [Keys.HorizontalPosition] = "Pozycja pozioma",
        [Keys.VerticalPosition] = "Pozycja pionowa",
        [Keys.InGameOverlay] = "Nakładka nad grą",
        [Keys.AllowTheAppToDisplayTranslationsOverOtherApps] = "Zezwól aplikacji wyświetlać tłumaczenie nad innymi aplikacjami.",
        [Keys.NotificationsSection] = "Powiadomienia",
        [Keys.AllowNotificationsAboutTheActiveTranslatorSession] = "Zezwól na powiadomienie o aktywnej sesji tłumacza.",
        [Keys.LatestTranslation] = "Ostatnie tłumaczenie",
        [Keys.MeasurementsAreUpdatedWhenTranslationCompletes] = "Pomiar jest aktualizowany po zakończeniu tłumaczenia.",
        [Keys.TotalSummary] = "Całość",
        [Keys.LatestApiKeyValidation] = "Ostatnie sprawdzenie klucza API",
        [Keys.ThemeSection] = "Motyw",
        [Keys.AccentSection] = "Akcent",
        [Keys.AppLanguage] = "Język aplikacji",
        [Keys.English] = "English",
        [Keys.Polish] = "Polski",
        [Keys.SystemDefault] = "Systemowy",
        [Keys.WelcomeToPikslovo] = "Witaj w Pikslovo",
        [Keys.PikslovoRecognizesTextOnYourGameScreenAndTranslatesItWithGoogleCloudTheScreenshotAndRecognizedTextAreSentToGoogleServicesOnlyWhileTranslating] = "Pikslovo rozpoznaje tekst na ekranie gry i tłumaczy go przez Google Cloud. Zrzut ekranu oraz rozpoznany tekst są wysyłane do usług Google tylko podczas tłumaczenia.",
        [Keys.Languages] = "Języki",
        [Keys.DuringAnActiveSessionAndroidDisplaysAPersistentNotificationItIndicatesThatPikslovoCanCaptureTheScreenForTranslation] = "Podczas aktywnej sesji Android wyświetla stałe powiadomienie. Informuje ono, że Pikslovo może przechwytywać ekran na potrzeby tłumaczenia.",
        [Keys.VisibleActiveSession] = "Widoczna aktywna sesja",
        [Keys.TheNotificationRemainsVisibleWhileTheTranslatorRunsInTheBackground] = "Powiadomienie pozostaje widoczne, gdy tłumacz działa w tle.",
        [Keys.SessionControl] = "Kontrola sesji",
        [Keys.YouCanStopTheActiveTranslatorSessionFromTheNotification] = "Z poziomu powiadomienia można zatrzymać aktywną sesję tłumacza.",
        [Keys.PikslovoNeedsPermissionToDisplayOverOtherAppsSoItCanShowTheTranslatedImageWithoutLeavingTheGame] = "Pikslovo potrzebuje zgody na wyświetlanie nad innymi aplikacjami, aby pokazać przetłumaczony obraz bez wychodzenia z gry.",
        [Keys.TranslationOverTheGame] = "Tłumaczenie nad grą",
        [Keys.TheResultWillAppearAsATemporaryOverlayOverTheCurrentScreen] = "Wynik pojawi się jako tymczasowa nakładka nad aktualnym ekranem.",
        [Keys.OnlyOnDemand] = "Tylko na żądanie",
        [Keys.TheOverlayIsShownOnlyAfterTranslationIsTriggered] = "Nakładka jest pokazywana wyłącznie po wywołaniu tłumaczenia.",
        [Keys.PikslovoRequiresYourOwnGoogleCloudApiKeyForTextRecognitionAndTranslationYouCanConfigureItNowOrLaterInSettingsTranslationWillNotWorkWithoutIt] = "Pikslovo wymaga własnego klucza Google Cloud API do rozpoznawania i tłumaczenia tekstu. Możesz skonfigurować go teraz albo później w ustawieniach. Bez klucza tłumaczenie nie będzie działać.",
        [Keys.Continue] = "Continue",
        [Keys.GrantPermission] = "Przyznaj uprawnienie",
        [Keys.NotSelected] = "Nie wybrano",
        [Keys.ThisWillClearOcrJpegCaptureRegionAndFloatingButtonSettingsTheApiKeyLanguagesHotkeyAndAppAppearanceWillRemainUnchanged] = "Ta operacja wyczyści ustawienia OCR, JPEG, obszaru przechwytywania i przycisku pływającego. Klucz API, języki, globalny skrót i wygląd aplikacji pozostaną bez zmian.",
        [Keys.OverlayPermissionIsAlreadyGranted] = "Uprawnienie nakładki jest już przyznane.",
        [Keys.OpeningAndroidOverlaySettings] = "Otwieram ustawienia nakładki Androida.",
        [Keys.NotificationPermissionIsAlreadyGranted] = "Uprawnienie powiadomień jest już przyznane.",
        [Keys.ShowingAndroidNotificationPermissionRequest] = "Wyświetlam prośbę Androida o zgodę na powiadomienia.",
        [Keys.ItIsVisibleDuringAnActiveSessionRegardlessOfTheGlobalHotkey] = "W aktywnej sesji jest widoczny niezależnie od globalnego skrótu.",
        [Keys.ItIsHiddenDuringAnActiveSessionWhenTheGlobalHotkeyIsEnabled] = "W aktywnej sesji jest ukryty, gdy globalny skrót jest włączony.",
        [Keys.ItIsVisibleDuringAnActiveSessionBecauseTheGlobalHotkeyIsDisabled] = "W aktywnej sesji jest widoczny, ponieważ globalny skrót jest wyłączony.",
        [Keys.Unknown] = "nieznana",
        [Keys.ExcludedDataApiKeyScreenContentOcrResultAndTranslatedText] = "Wykluczone dane: klucz API, treść ekranu, wynik OCR i tekst tłumaczenia.",
        [Keys.GoogleCloudApi] = "Google Cloud API",
        [Keys.GoogleCloudApiKey] = "Google Cloud API key",
        [Keys.OcrImageSize] = "Rozmiar obrazu OCR",
        [Keys.CloudVisionOcrLabel] = "Cloud Vision OCR",
        [Keys.CloudTranslationLabel] = "Cloud Translation",
        [Keys.OverlayRender] = "Render nakładki",
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        [Keys.CheckKey] = "Check key",
        [Keys.Checking] = "Checking...",
        [Keys.SourceLanguage] = "Source language",
        [Keys.TargetLanguage] = "Target language",
        [Keys.MissingApiKeyTitle] = "Missing API key",
        [Keys.MissingApiKeyMessage] = "Enter a Google Cloud API key to check it.",
        [Keys.KeyDoesNotWorkTitle] = "Key does not work",
        [Keys.NoConnectionTitle] = "No connection",
        [Keys.NoConnectionMessage] = "Could not connect to Google Cloud. Check your internet connection and try again.",
        [Keys.TimeoutTitle] = "Timed out",
        [Keys.TimeoutMessage] = "Key validation took too long. Try again with a stable connection.",
        [Keys.KeyWorksTitle] = "Key works",
        [Keys.KeyWorksMessage] = "The key can access Cloud Translation API and Cloud Vision API.",
        [Keys.Save] = "Save",
        [Keys.Cancel] = "Cancel",
        [Keys.Close] = "Close",
        [Keys.Restore] = "Restore",
        [Keys.RestoreDefaultsQuestion] = "Restore default settings?",
        [Keys.RestoreDefaultsMessage] = "OCR settings, including JPEG compression and image quality, overlay, capture region and floating button will be reset. The API key, languages, global shortcut and app appearance will remain unchanged.",
        [Keys.AndroidActivityNotReady] = "Android activity is not ready. Close and reopen the app.",
        [Keys.AndroidActivityNotReadyYet] = "Android activity is not ready yet.",
        [Keys.TranslatorSessionStopped] = "Translator session stopped.",
        [Keys.OpeningScreenSharingDialog] = "Opening Android's screen sharing dialog.",
        [Keys.NotificationPermissionDenied] = "Permission was not granted. You can try again.",
        [Keys.SetShortcutOrDisableHotkey] = "Set a shortcut or disable the global shortcut.",
        [Keys.EnterApiKeyAndLanguages] = "Enter an API key and select both languages.",
        [Keys.SettingsExported] = "Settings exported to a JSON file.",
        [Keys.SettingsImported] = "Settings imported from a JSON file.",
        [Keys.DefaultConfigurationRestored] = "Default configuration settings restored.",
        [Keys.OpeningAccessibilitySettings] = "Opening Android accessibility settings.",
        [Keys.NotSet] = "Not set",
        [Keys.NoMeasurement] = "No measurement",
        [Keys.SettingsReadFailed] = "Settings cannot be read yet: {0}",
        [Keys.OpenGoogleCloudPageFailed] = "Cannot open the Google Cloud page: {0}",
        [Keys.OpenPikslovoPageFailed] = "Cannot open the Pikslovo page: {0}",
        [Keys.OpenSupportPageFailed] = "Cannot open the support page: {0}",
        [Keys.HotkeyBlockedHelp] = "How to unlock shortcut setup",
        [Keys.IfShortcutConfigurationIsBlockedOpenThisGuideToUnlockItInAndroid] = "If shortcut setup is blocked, open this guide to learn how to unlock it in Android.",
        [Keys.AccessibilityPermissionIsAlreadyGranted] = "Accessibility permission is already granted.",
        [Keys.ApiKeyNoAccess] = "The key cannot access {0}. Check that the key is valid and that this API is enabled in the Google Cloud project.",
        [Keys.ApiKeyCheckFailed] = "Could not check access to {0}. Google returned error {1}.",
        [Keys.StartScreenCaptureFailed] = "Cannot start screen capture: {0}",
        [Keys.ExportDiagnosticsFailed] = "Cannot export diagnostics log: {0}",
        [Keys.ExportSettingsFailed] = "Cannot export settings: {0}",
        [Keys.ImportSettingsFailed] = "Cannot import settings: {0}",
        [Keys.OpenFilePickerFailed] = "Cannot open the file picker: {0}",
        [Keys.RestoreSettingsFailed] = "Cannot restore settings: {0}",
        [Keys.OpenOverlaySettingsFailed] = "Cannot open overlay settings: {0}",
        [Keys.RequestNotificationPermissionFailed] = "Cannot request notification permission: {0}",
        [Keys.OpenAccessibilitySettingsFailed] = "Cannot open accessibility settings: {0}",
        [Keys.DiagnosticsReportTitle] = "Pikslovo - diagnostics report",
        [Keys.DiagnosticsGeneratedAtUtc] = "Generated (UTC): {0}",
        [Keys.DiagnosticsApplication] = "Application: {0}",
        [Keys.DiagnosticsDevice] = "Device: {0}",
        [Keys.DiagnosticsActiveSession] = "Active translator session: {0}",
        [Keys.DiagnosticsOverlayPermission] = "Overlay permission: {0}",
        [Keys.DiagnosticsNotificationPermission] = "Notification permission: {0}",
        [Keys.DiagnosticsLastCaptureAttempt] = "Last capture attempt: status={0}, attempts={1}, elapsed={2}",
        [Keys.DiagnosticsLatestMeasurements] = "Latest measurements:",
        [Keys.DiagnosticsCaptureStatusSuccess] = "success",
        [Keys.DiagnosticsCaptureStatusNoFreshFrame] = "no fresh frame",
        [Keys.DiagnosticsCaptureStatusFailed] = "read failure",
        [Keys.DiagnosticsLatestCapture] = "Latest capture",
        [Keys.DiagnosticsLatestCaptureDescription] = "Status of the most recent attempt to get a frame from the MediaProjection session.",
        [Keys.DiagnosticsCaptureStatusLabel] = "Status",
        [Keys.DiagnosticsCaptureAttemptsLabel] = "Attempts",
        [Keys.DiagnosticsCaptureElapsedLabel] = "Wait time",
        [Keys.CapturePlusEncoding] = "Capture + encoding",
        [Keys.OcrImageEncoding] = "OCR image encoding",
        [Keys.TotalTranslation] = "Total translation",
        [Keys.ApiKeyValidation] = "API key validation",
        [Keys.ThemeSystem] = "System",
        [Keys.ThemeDark] = "Dark",
        [Keys.ThemeLight] = "Light",
        [Keys.AccentCoral] = "Coral",
        [Keys.AccentAmber] = "Amber",
        [Keys.AccentLime] = "Lime",
        [Keys.AccentMint] = "Mint",
        [Keys.AccentTeal] = "Teal",
        [Keys.AccentAqua] = "Aqua",
        [Keys.AccentSky] = "Sky blue",
        [Keys.AccentSteel] = "Steel",
        [Keys.AccentOrchid] = "Orchid",
        [Keys.AccentRose] = "Rose",
        [Keys.AccentLavender] = "Lavender",
        [Keys.UserOcrSettings] = "User OCR settings:",
        [Keys.OcrConfidence] = "OCR confidence: {0}",
        [Keys.OcrImageScale] = "OCR image scale: {0}",
        [Keys.DialogGroupingStrength] = "Dialog grouping strength: {0}",
        [Keys.FontScale] = "Font scale: {0}",
        [Keys.HideIdenticalTranslations] = "Hide identical translations: {0}",
        [Keys.OcrImageEncodingFormat] = "OCR image encoding: {0}",
        [Keys.NoData] = "no data",
        [Keys.Yes] = "yes",
        [Keys.No] = "no",
        [Keys.FillApiKeyAndLanguages] = "Enter the API key and both languages before starting translation.",
        [Keys.GoogleTranslationIncomplete] = "Google Translation returned an incomplete response.",
        [Keys.CloudTranslationRejected] = "Cloud Translation API rejected the request ({0} {1}): {2}",
        [Keys.CloudTranslationIncomplete] = "Cloud Translation API returned an incomplete response.",
        [Keys.CloudVisionRejected] = "Cloud Vision API rejected the screenshot ({0} {1}): {2}",
        [Keys.CloudVisionError] = "Cloud Vision API: {0}",
        [Keys.UnknownOcrError] = "Unknown OCR error.",
        [Keys.CannotSaveSelectedFile] = "Cannot save the selected file.",
        [Keys.CannotReadSelectedFile] = "Cannot read the selected file.",
        [Keys.ShareDiagnostics] = "Share diagnostics log",
        [Keys.CannotOpenSharePanel] = "Cannot open the share panel.",
        [Keys.CouldNotStartSession] = "Could not start session: {0}",
        [Keys.CannotReadScreenSize] = "Cannot read screen size.",
        [Keys.CouldNotEncodeOcrImage] = "Could not encode the OCR image.",
        [Keys.ActiveTranslatorSession] = "Active translator session",
        [Keys.PikslovoIsActive] = "Pikslovo is active",
        [Keys.HotkeyAndFloatingButtonReady] = "The hotkey and floating button are ready.",
        [Keys.Stop] = "Stop",
        [Keys.HoldKeysForTwoSeconds] = "Hold key(s) for 1 second",
        [Keys.SetShortcut] = "Set shortcut",
        [Keys.TapToSetShortcut] = "Tap to set shortcut",
        [Keys.TranslateScreen] = "Translate screen",
        [Keys.EditCaptureRegion] = "Edit capture region",
        [Keys.StopTranslator] = "Stop translator",
        [Keys.TranslationInProgress] = "Translation in progress",
        [Keys.ReturnToGame] = "Return to game",
        [Keys.DragDialogRegionCorners] = "Drag the dialog region corners",
        [Keys.SaveRegion] = "Save region",
        [Keys.CancelRegionSelection] = "Cancel region selection",
        [Keys.RestoreFullScreenRegion] = "Restore full-screen region",
        [Keys.ConfigurationFileMissing] = "The file does not contain configuration.",
        [Keys.UnsupportedConfigurationVersion] = "This configuration file comes from an unsupported app version.",
        [Keys.IncompleteConfigurationFile] = "The configuration file is incomplete.",
        [Keys.InvalidOcrOrOverlaySettings] = "The file contains invalid OCR or overlay settings.",
        [Keys.InvalidFloatingButtonSettings] = "The file contains invalid floating button settings.",
        [Keys.InvalidCaptureRegion] = "The file contains an invalid capture region.",
        [Keys.CannotSaveAppConfigurationState] = "Cannot save app configuration state.",
        [Keys.CannotSaveAppSettings] = "Cannot save app settings.",
        [Keys.KeystoreMissingInitializationVector] = "Android Keystore did not return an initialization vector.",
        [Keys.KeystoreDidNotEncryptApiKey] = "Android Keystore did not encrypt the API key.",
        [Keys.CannotReadKeystoreKey] = "Cannot read the Android Keystore key.",
        [Keys.ScreenCaptureConsentExpired] = "Screen recording consent expired. Restart the translator and accept the new prompt.",
        [Keys.ScreenCaptureConsentDenied] = "Screen capture permission was not granted.",
        [Keys.ScreenCaptureStartFailed] = "Could not start screen capture.",
        [Keys.TranslatorIsActive] = "Translator is active.",
        [Keys.DialogRegionSaved] = "Dialog region saved.",
        [Keys.GrantOverlayPermission] = "Grant permission to display over other apps.",
        [Keys.ScreenFrameCaptureFailed] = "Could not capture the screen frame.",
        [Keys.NoTextFoundOnScreen] = "No text found on screen.",
        [Keys.Translator] = "Translator",
        [Keys.BackToSettings] = "Back to settings",
        [Keys.Settings] = "Settings",
        [Keys.Permissions] = "Permissions",
        [Keys.InGameOverlayAndNotifications] = "In-game overlay and notifications",
        [Keys.KeyForTextRecognitionAndTranslation] = "Key for text recognition and translation",
        [Keys.Translation] = "Translation",
        [Keys.SourceAndTargetLanguages] = "Source and target languages",
        [Keys.GlobalHotkey] = "Global shortcut",
        [Keys.ShortcutToShowTheTranslation] = "Shortcut to show the translation",
        [Keys.FloatingButton] = "Floating button",
        [Keys.VisibilitySizeAndPositionOnScreen] = "Visibility, size and position on screen",
        [Keys.TextProcessing] = "Text processing",
        [Keys.OcrConfidenceImageScaleDialogGroupingAndOverlay] = "OCR confidence, image scale, dialog grouping and overlay",
        [Keys.AppAppearance] = "App appearance",
        [Keys.Configurations] = "Configurations",
        [Keys.ExportSettings] = "Export settings",
        [Keys.SaveOcrJpegCompressionRegionAndButtonSettingsToAJsonFile] = "Save OCR, JPEG compression, region and button settings to a JSON file.",
        [Keys.ImportSettings] = "Import settings",
        [Keys.LoadOcrJpegCompressionAndTheRemainingConfigurationFromAJsonFile] = "Load OCR, JPEG compression and the remaining configuration from a JSON file.",
        [Keys.RestoreDefaults] = "Restore defaults",
        [Keys.ClearOcrJpegCompressionRegionAndButtonSettings] = "Clear OCR, JPEG compression, region and button settings.",
        [Keys.Support] = "Support",
        [Keys.Diagnostics] = "Diagnostics",
        [Keys.LatestTranslationAndApiKeyValidationTimings] = "Latest translation and API key validation timings",
        [Keys.PikslovoGitHub] = "Pikslovo GitHub",
        [Keys.SourceCodeBugReportsAndProjectDevelopment] = "Source code, bug reports and project development.",
        [Keys.SupportPikslovo] = "Support Pikslovo",
        [Keys.IfYouLikeThisAppSupportItsFurtherDevelopment] = "If you like this app, support its further development.",
        [Keys.ExportDiagnosticsLog] = "Export diagnostics log",
        [Keys.SaveASafeReportWithMeasurementsWithoutTheApiKeyOrScreenContent] = "Save a safe report with measurements, without the API key or screen content.",
        [Keys.ImportantNeverShareThisKeyWithAnyone] = "Important: never share this key with anyone.",
        [Keys.ShowOrHideApiKey] = "Show or hide API key",
        [Keys.GetAGoogleCloudApiKey] = "Get a Google Cloud API key",
        [Keys.GoogleCloudApiKeySetupGuide] = "How to get a Google Cloud API key",
        [Keys.OpenStepByStepInstructionsForCreatingAnApiKey] = "Open step-by-step instructions for creating a Google Cloud API key.",
        [Keys.RecognitionConfidence] = "Recognition confidence",
        [Keys.OcrImageScaleSetting] = "OCR image scale",
        [Keys.CompressOcrImageToJpeg] = "Compress OCR image to JPEG",
        [Keys.ReducesDataSentToGoogleCloud] = "Reduces data sent to Google Cloud.",
        [Keys.JpegQuality] = "JPEG quality",
        [Keys.TextGroupingStrength] = "Text grouping strength",
        [Keys.FontScaleSetting] = "Font scale",
        [Keys.HideIdenticalTranslationsSetting] = "Hide identical translations",
        [Keys.DoNotShowTextWhenTheTranslationIsIdentical] = "Do not show text when the translation is identical.",
        [Keys.AccessibilitySettings] = "Accessibility settings",
        [Keys.EnableTheSystemServiceForTheGlobalHotkey] = "Enable the system service for the global shortcut.",
        [Keys.EnableGlobalHotkey] = "Enable global shortcut",
        [Keys.LetsYouTriggerTranslationOutsideTheApp] = "Lets you trigger translation outside the app.",
        [Keys.ShortcutKey] = "Shortcut key",
        [Keys.AlwaysShowButton] = "Always show button",
        [Keys.ButtonSize] = "Button size",
        [Keys.HorizontalPosition] = "Horizontal position",
        [Keys.VerticalPosition] = "Vertical position",
        [Keys.InGameOverlay] = "In-game overlay",
        [Keys.AllowTheAppToDisplayTranslationsOverOtherApps] = "Allow the app to display translations over other apps.",
        [Keys.NotificationsSection] = "Notifications",
        [Keys.AllowNotificationsAboutTheActiveTranslatorSession] = "Allow notifications about the active translator session.",
        [Keys.LatestTranslation] = "Latest translation",
        [Keys.MeasurementsAreUpdatedWhenTranslationCompletes] = "Measurements are updated when translation completes.",
        [Keys.TotalSummary] = "Total",
        [Keys.LatestApiKeyValidation] = "Latest API key validation",
        [Keys.ThemeSection] = "Theme",
        [Keys.AccentSection] = "Accent",
        [Keys.AppLanguage] = "App language",
        [Keys.English] = "English",
        [Keys.Polish] = "Polish",
        [Keys.SystemDefault] = "System default",
        [Keys.WelcomeToPikslovo] = "Welcome to Pikslovo",
        [Keys.PikslovoRecognizesTextOnYourGameScreenAndTranslatesItWithGoogleCloudTheScreenshotAndRecognizedTextAreSentToGoogleServicesOnlyWhileTranslating] = "Pikslovo recognizes text on your game screen and translates it with Google Cloud. The screenshot and recognized text are sent to Google services only while translating.",
        [Keys.Languages] = "Languages",
        [Keys.DuringAnActiveSessionAndroidDisplaysAPersistentNotificationItIndicatesThatPikslovoCanCaptureTheScreenForTranslation] = "During an active session, Android displays a persistent notification. It indicates that Pikslovo can capture the screen for translation.",
        [Keys.VisibleActiveSession] = "Visible active session",
        [Keys.TheNotificationRemainsVisibleWhileTheTranslatorRunsInTheBackground] = "The notification remains visible while the translator runs in the background.",
        [Keys.SessionControl] = "Session control",
        [Keys.YouCanStopTheActiveTranslatorSessionFromTheNotification] = "You can stop the active translator session from the notification.",
        [Keys.PikslovoNeedsPermissionToDisplayOverOtherAppsSoItCanShowTheTranslatedImageWithoutLeavingTheGame] = "Pikslovo needs permission to display over other apps so it can show the translated image without leaving the game.",
        [Keys.TranslationOverTheGame] = "Translation over the game",
        [Keys.TheResultWillAppearAsATemporaryOverlayOverTheCurrentScreen] = "The result will appear as a temporary overlay over the current screen.",
        [Keys.OnlyOnDemand] = "Only on demand",
        [Keys.TheOverlayIsShownOnlyAfterTranslationIsTriggered] = "The overlay is shown only after translation is triggered.",
        [Keys.PikslovoRequiresYourOwnGoogleCloudApiKeyForTextRecognitionAndTranslationYouCanConfigureItNowOrLaterInSettingsTranslationWillNotWorkWithoutIt] = "Pikslovo requires your own Google Cloud API key for text recognition and translation. You can configure it now or later in Settings. Translation will not work without it.",
        [Keys.Continue] = "Continue",
        [Keys.GrantPermission] = "Grant permission",
        [Keys.NotSelected] = "Not selected",
        [Keys.ThisWillClearOcrJpegCaptureRegionAndFloatingButtonSettingsTheApiKeyLanguagesHotkeyAndAppAppearanceWillRemainUnchanged] = "This will clear OCR, JPEG, capture region and floating button settings. The API key, languages, global shortcut and app appearance will remain unchanged.",
        [Keys.OverlayPermissionIsAlreadyGranted] = "Overlay permission is already granted.",
        [Keys.OpeningAndroidOverlaySettings] = "Opening Android overlay settings.",
        [Keys.NotificationPermissionIsAlreadyGranted] = "Notification permission is already granted.",
        [Keys.ShowingAndroidNotificationPermissionRequest] = "Showing Android's notification permission request.",
        [Keys.ItIsVisibleDuringAnActiveSessionRegardlessOfTheGlobalHotkey] = "It is visible during an active session regardless of the global shortcut.",
        [Keys.ItIsHiddenDuringAnActiveSessionWhenTheGlobalHotkeyIsEnabled] = "It is hidden during an active session when the global shortcut is enabled.",
        [Keys.ItIsVisibleDuringAnActiveSessionBecauseTheGlobalHotkeyIsDisabled] = "It is visible during an active session because the global shortcut is disabled.",
        [Keys.Unknown] = "unknown",
        [Keys.ExcludedDataApiKeyScreenContentOcrResultAndTranslatedText] = "Excluded data: API key, screen content, OCR result and translated text.",
        [Keys.OcrImageSize] = "OCR image size",
        [Keys.OverlayRender] = "Overlay render",
    };

    public static AppLanguageMode LanguageMode => _languageMode;

    public static bool IsCurrentLanguagePolish => UsesPolish;

    public static void SetLanguageMode(AppLanguageMode languageMode) => _languageMode = languageMode;

    public static string Get(string key)
    {
        var normalizedKey = NormalizeKey(key);

        var current = UsesPolish ? Polish : English;
        if (current.TryGetValue(normalizedKey, out var localized))
        {
            return localized;
        }

        if (Polish.TryGetValue(normalizedKey, out var fallback))
        {
            return fallback;
        }

        return string.IsNullOrWhiteSpace(key) ? string.Empty : $"!!{key}!!";
    }

    public static bool HasKey(string? key)
    {
        var normalizedKey = NormalizeKey(key);
        return !string.IsNullOrEmpty(normalizedKey) && (Polish.ContainsKey(normalizedKey) || English.ContainsKey(normalizedKey));
    }

    public static string Format(string key, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), arguments);

    public static string GetThemeModeLabel(AppThemeMode mode) => Get(mode switch
    {
        AppThemeMode.Dark => Keys.ThemeDark,
        AppThemeMode.Light => Keys.ThemeLight,
        _ => Keys.ThemeSystem
    });

    public static string GetAccentLabel(AppAccent accent) => Get(accent switch
    {
        AppAccent.Coral => Keys.AccentCoral,
        AppAccent.Amber => Keys.AccentAmber,
        AppAccent.Lime => Keys.AccentLime,
        AppAccent.Mint => Keys.AccentMint,
        AppAccent.Teal => Keys.AccentTeal,
        AppAccent.Aqua => Keys.AccentAqua,
        AppAccent.Sky => Keys.AccentSky,
        AppAccent.Steel => Keys.AccentSteel,
        AppAccent.Orchid => Keys.AccentOrchid,
        AppAccent.Rose => Keys.AccentRose,
        _ => Keys.AccentLavender
    });

    public static string GetLanguageName(string languageCode) => LanguageCatalog.GetDisplayName(languageCode);

    public static string GetBooleanLabel(bool value) => Get(value ? Keys.Yes : Keys.No);

    private static string NormalizeKey(string? key) => key?.Trim() ?? string.Empty;

    private static bool UsesPolish => _languageMode switch
    {
        AppLanguageMode.Polish => true,
        AppLanguageMode.English => false,
        _ => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("pl", StringComparison.OrdinalIgnoreCase),
    };
}
