<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0</TargetFrameworks>
    <BaseOutputPath>../../bin/Pikslovo/</BaseOutputPath>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>Pikslovo</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>app.pikslovo</ApplicationId>
    <!-- Versions -->
    <Version>1.0.0</Version>
    <VersionMajor>$([System.Version]::Parse('$(Version)').Major)</VersionMajor>
    <VersionMinor>$([System.Version]::Parse('$(Version)').Minor)</VersionMinor>
    <VersionPatch>$([System.Version]::Parse('$(Version)').Build)</VersionPatch>
    <ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
    <ApplicationVersion>$([System.String]::Format('{0}{1:00}{2:00}', $(VersionMajor), $(VersionMinor), $(VersionPatch)))</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>Pikslovo</ApplicationPublisher>
    <!-- Package Description -->
    <Description>Pikslovo powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Material;
      Mvvm;
    </UnoFeatures>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <SupportedOSPlatformVersion>31</SupportedOSPlatformVersion>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <DisableDefaultUnoResizetizerItems>true</DisableDefaultUnoResizetizerItems>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <AndroidResource Include="Assets/Icons/icon.png" Link="Resources/drawable/icon.png" />
  </ItemGroup>

</Project>
